#!/bin/sh

echo "window.RUNTIME_REACT_APP_SSO_HOST='${REACT_APP_SSO_HOST}'";
echo "window.RUNTIME_REACT_APP_SSO_REALM='${REACT_APP_SSO_REALM}'";
echo "window.RUNTIME_REACT_APP_SSO_CLIENT='${REACT_APP_SSO_CLIENT}'";
echo "window.RUNTIME_REACT_APP_API_HOST='${REACT_APP_API_HOST}'";