-- =============================================
-- Author:		Ben Driver
-- Create date: 2020-04-06
-- Updates: 
-- 
-- Description:	
--- Revise ACTIVITY CODE values to latest
--- Populate SP_THRESHOLD_LEVEL for each ACTIVITY CODE
-- =============================================

USE HMR_DEV; -- uncomment appropriate instance
--USE HMR_TST;
--USE HMR_UAT;
--USE HMR_PRD;
GO


/* Load user context variables. */

DECLARE @utcdate DATETIME = (SELECT getutcdate() AS utcdate)
DECLARE @app_guid UNIQUEIDENTIFIER = (SELECT CASE WHEN SUSER_SID() IS NOT NULL THEN SUSER_SID() ELSE (SELECT CONVERT(uniqueidentifier,STUFF(STUFF(STUFF(STUFF('B00D00A0AC0A0D0C00DD00F0D0C00000',9,0,'-'),14,0,'-'),19,0,'-'),24,0,'-'))) END AS  app_guid)
DECLARE @app_user VARCHAR(30) = (SELECT CASE WHEN SUBSTRING(SUSER_NAME(),CHARINDEX('\',SUSER_NAME())+1,LEN(SUSER_NAME())) IS NOT NULL THEN SUBSTRING(SUSER_NAME(),CHARINDEX('\',SUSER_NAME())+1,LEN(SUSER_NAME())) ELSE CURRENT_USER END AS app_user)
DECLARE @app_user_dir VARCHAR(12) = (SELECT CASE WHEN LEN(SUBSTRING(SUSER_NAME(),0,CHARINDEX('\',SUSER_NAME(),0)))>1 THEN SUBSTRING(SUSER_NAME(),0,CHARINDEX('\',SUSER_NAME(),0)) ELSE 'WIN AUTH' END AS app_user_dir)

/*  Revised initial Spatial Threashold levels for all Activity Codes  */

UPDATE HMR_ACTIVITY_CODE 
	SET SP_THRESHOLD_LEVEL = 'Level 1', 
	APP_LAST_UPDATE_USERID = @app_user, 
	APP_LAST_UPDATE_TIMESTAMP = @utcdate, 
	APP_LAST_UPDATE_USER_GUID = @app_guid, 
	APP_LAST_UPDATE_USER_DIRECTORY = @app_user_dir,
	CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1
WHERE 
	LOCATION_CODE_ID IN (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C');
	
UPDATE HMR_ACTIVITY_CODE 
	SET SP_THRESHOLD_LEVEL = NULL, 
	APP_LAST_UPDATE_USERID = @app_user, 
	APP_LAST_UPDATE_TIMESTAMP = @utcdate, 
	APP_LAST_UPDATE_USER_GUID = @app_guid, 
	APP_LAST_UPDATE_USER_DIRECTORY = @app_user_dir,
	CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1
WHERE 
	LOCATION_CODE_ID NOT IN (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C');


/*  Revised Spatial Threashold level for activities that occur away from the driven highway */

UPDATE HMR_ACTIVITY_CODE 
	SET SP_THRESHOLD_LEVEL = 'Level 4', 
	APP_LAST_UPDATE_USERID = @app_user, 
	APP_LAST_UPDATE_TIMESTAMP = @utcdate, 
	APP_LAST_UPDATE_USER_GUID = @app_guid, 
	APP_LAST_UPDATE_USER_DIRECTORY = @app_user_dir,
	CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1
WHERE 
	ACTIVITY_NUMBER IN ('301203','401301','404200','404201','918202','920201','920202','922200')
	AND LOCATION_CODE_ID IN (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C');

GO

/* Delete Activity Codes that will be revised */

DELETE FROM HMR_ACTIVITY_CODE WHERE ACTIVITY_NUMBER IN ('107301','109201','110203','110306','110307','202206','304200','401301','606200','612200','612202','999400','999401','999402','999403','999404','999405','901200','922200','926200','930200','931200','932300','933300');
GO

/* Delete abandoned activity codes */

DELETE FROM HMR_ACTIVITY_CODE WHERE ACTIVITY_NUMBER IN ('190201','702400','922000','926300');
GO

/* Load user context variables. */

DECLARE @utcdate DATETIME = (SELECT getutcdate() AS utcdate)
DECLARE @app_guid UNIQUEIDENTIFIER = (SELECT CASE WHEN SUSER_SID() IS NOT NULL THEN SUSER_SID() ELSE (SELECT CONVERT(uniqueidentifier,STUFF(STUFF(STUFF(STUFF('B00D00A0AC0A0D0C00DD00F0D0C00000',9,0,'-'),14,0,'-'),19,0,'-'),24,0,'-'))) END AS  app_guid)
DECLARE @app_user VARCHAR(30) = (SELECT CASE WHEN SUBSTRING(SUSER_NAME(),CHARINDEX('\',SUSER_NAME())+1,LEN(SUSER_NAME())) IS NOT NULL THEN SUBSTRING(SUSER_NAME(),CHARINDEX('\',SUSER_NAME())+1,LEN(SUSER_NAME())) ELSE CURRENT_USER END AS app_user)
DECLARE @app_user_dir VARCHAR(12) = (SELECT CASE WHEN LEN(SUBSTRING(SUSER_NAME(),0,CHARINDEX('\',SUSER_NAME(),0)))>1 THEN SUBSTRING(SUSER_NAME(),0,CHARINDEX('\',SUSER_NAME(),0)) ELSE 'WIN AUTH' END AS app_user_dir)

UPDATE HMR_ACTIVITY_CODE_HIST 
	SET END_DATE = @utcdate,
	END_DATE_HIST = @utcdate
      ,CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER+1
  FROM HMR_ACTIVITY_CODE_HIST
  WHERE ACTIVITY_NUMBER IN ('190201','702400','922000','926300') AND END_DATE IS NULL
  GO


/* Load user context variables. */

DECLARE @utcdate DATETIME = (SELECT getutcdate() AS utcdate)
DECLARE @app_guid UNIQUEIDENTIFIER = (SELECT CASE WHEN SUSER_SID() IS NOT NULL THEN SUSER_SID() ELSE (SELECT CONVERT(uniqueidentifier,STUFF(STUFF(STUFF(STUFF('B00D00A0AC0A0D0C00DD00F0D0C00000',9,0,'-'),14,0,'-'),19,0,'-'),24,0,'-'))) END AS  app_guid)
DECLARE @app_user VARCHAR(30) = (SELECT CASE WHEN SUBSTRING(SUSER_NAME(),CHARINDEX('\',SUSER_NAME())+1,LEN(SUSER_NAME())) IS NOT NULL THEN SUBSTRING(SUSER_NAME(),CHARINDEX('\',SUSER_NAME())+1,LEN(SUSER_NAME())) ELSE CURRENT_USER END AS app_user)
DECLARE @app_user_dir VARCHAR(12) = (SELECT CASE WHEN LEN(SUBSTRING(SUSER_NAME(),0,CHARINDEX('\',SUSER_NAME(),0)))>1 THEN SUBSTRING(SUSER_NAME(),0,CHARINDEX('\',SUSER_NAME(),0)) ELSE 'WIN AUTH' END AS app_user_dir)

/* Insert revised ACTIVITY_CODE values */

INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('107301', 'Surface Cleaning Remove Accumulations (additional)', 'sh km', 'Q', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Line', 'Level 1', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('109201', 'Cattle Guard Repair', 'num', 'R', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'A'), NULL, NULL, 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('110203', 'Roundabout Maintenance', 'hours', 'R', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'A'), NULL, NULL, 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('110306', 'traffic island - replace', 'm2', 'Q', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point', 'Level 1', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('110307', 'traffic island - new', 'm2', 'Q', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point', 'Level 1', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('202206', 'Culvert Stakes and Markers', 'num', 'R', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'A'), NULL, NULL, 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('304200', 'Highway Snow Avalanche Deposits Removal', 'hours', 'R', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 1', 1, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('401301', 'cut vegetation (Rest Areas/other specified locations)', 'm2', 'Q', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 4', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('606200', 'Bailey/Acrow Parts/Maintenance', 'site', 'R', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point', 'Level 1', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('612200', 'Bridge Posts Maintenance', 'site', 'R', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point', 'Level 1', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('612202', 'Bridge Rail Maintenance', 'site', 'R', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point', 'Level 1', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('999400', 'H0200 – Routine Maintenance Services above RMSC', 'dollars', 'A', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 1', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('999401', 'H0200 – Major Event Response', 'dollars', 'A', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 1', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('999402', 'H0200 – Maintenance Services on Class 8/F', 'dollars', 'A', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 1', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('999403', 'H0200 – More Quantified', 'dollars', 'A', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 1', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('999404', 'H0200 – Designated First Nations Services', 'dollars', 'A', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 1', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('999405', 'H0200 – Other', 'dollars', 'A', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 1', 0, 'Province wide' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('901200', 'Arrestor Bed Incident Response', 'ea', 'R', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point', 'Level 1', 0, 'Local Area Specification' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('922200', 'Snow Shed Maintain, repair or replace Snow Shed components', 'ea', 'R', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point', 'Level 4', 0, 'Local Area Specification' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('926200', 'Bridge Patrol', 'hours', 'R', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 1', 0, 'Local Area Specification' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('930200', 'Median & interchange vegetation control', 'site', 'R', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 1', 0, 'Local Area Specification' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('931200', 'Median cleaning', 'site', 'R', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 1', 0, 'Local Area Specification' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('932300', 'Refuse and trash – removal – demonstration site clean up', 'ea', 'Q', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 1', 0, 'Local Area Specification' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);
INSERT INTO HMR_ACTIVITY_CODE (ACTIVITY_NUMBER, ACTIVITY_NAME, UNIT_OF_MEASURE, MAINTENANCE_TYPE, LOCATION_CODE_ID, FEATURE_TYPE, SP_THRESHOLD_LEVEL, IS_SITE_NUM_REQUIRED, ACTIVITY_APPLICATION, APP_CREATE_USERID, APP_CREATE_TIMESTAMP, APP_CREATE_USER_GUID, APP_CREATE_USER_DIRECTORY, APP_LAST_UPDATE_USERID, APP_LAST_UPDATE_TIMESTAMP, APP_LAST_UPDATE_USER_GUID, APP_LAST_UPDATE_USER_DIRECTORY) VALUES ('933300', 'Reclaimed Asphalt Pavement', 'tonne', 'Q', (SELECT LOCATION_CODE_ID FROM HMR_LOCATION_CODE WHERE dbo.HMR_LOCATION_CODE.LOCATION_CODE = 'C'), 'Point/Line', 'Level 1', 0, 'Local Area Specification' , @app_user, @utcdate, @app_guid, @app_user_dir, @app_user, @utcdate, @app_guid, @app_user_dir);


GO
