apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name | default "postgresql" }}{{ .Values.suffix }}
  labels:
    app: {{ .Values.postgresql.name | default "postgresql" }}{{ .Values.suffix }}
spec:
  selector:
    app: {{ .Values.postgresql.name | default "postgresql" }}{{ .Values.suffix }}
  ports:
  - name: db
    port: 5432
    targetPort: db
    protocol: TCP
  clusterIP: None
