-- =============================================
-- Author:		Ayodeji Kuponiyi
-- Create date: 2020-05-13
-- Update date: 2020-05-20



-- Comments: 
--	Original:
	--Deleting submission entries in all relevant tables on or before May 06 2020 for SA 19
--	Updates 2020-05-20: 
	--Included May 07 and SA 14
-- =============================================

USE HMR_DEV; -- uncomment appropriate instance
--USE HMR_TST;
--USE HMR_UAT;
--USE HMR_PRD;
GO


DELETE HMR_WORK_REPORT

WHERE EXISTS

(
	SELECT *

	FROM  [dbo].[HMR_SUBMISSION_OBJECT] so

	WHERE so.SUBMISSION_OBJECT_ID = HMR_WORK_REPORT.SUBMISSION_OBJECT_ID

		AND so.SERVICE_AREA_NUMBER IN (14,19)
		AND FORMAT(so.APP_CREATE_TIMESTAMP, 'dd-MM-yyyy') <= '07-MAY-2020'
)

DELETE HMR_WORK_REPORT_HIST

WHERE EXISTS

(
	SELECT *

	FROM  [dbo].[HMR_SUBMISSION_OBJECT] so

	WHERE so.SUBMISSION_OBJECT_ID = HMR_WORK_REPORT_HIST.SUBMISSION_OBJECT_ID

		AND so.SERVICE_AREA_NUMBER IN (14,19)
		AND FORMAT(so.APP_CREATE_TIMESTAMP, 'dd-MM-yyyy') <= '07-MAY-2020'
)


DELETE HMR_ROCKFALL_REPORT

WHERE EXISTS

(
	SELECT *

	FROM  [dbo].[HMR_SUBMISSION_OBJECT] so

	WHERE so.SUBMISSION_OBJECT_ID = HMR_ROCKFALL_REPORT.SUBMISSION_OBJECT_ID

		AND so.SERVICE_AREA_NUMBER IN (14,19)
		AND FORMAT(so.APP_CREATE_TIMESTAMP, 'dd-MM-yyyy') <= '07-MAY-2020'
)

DELETE HMR_ROCKFALL_REPORT_HIST

WHERE EXISTS

(
	SELECT *

	FROM  [dbo].[HMR_SUBMISSION_OBJECT] so

	WHERE so.SUBMISSION_OBJECT_ID = HMR_ROCKFALL_REPORT_HIST.SUBMISSION_OBJECT_ID

		AND so.SERVICE_AREA_NUMBER IN (14,19)
		AND FORMAT(so.APP_CREATE_TIMESTAMP, 'dd-MM-yyyy') <= '07-MAY-2020'
)


DELETE HMR_WILDLIFE_REPORT

WHERE EXISTS

(
	SELECT *

	FROM  [dbo].[HMR_SUBMISSION_OBJECT] so

	WHERE so.SUBMISSION_OBJECT_ID = HMR_WILDLIFE_REPORT.SUBMISSION_OBJECT_ID

		AND so.SERVICE_AREA_NUMBER IN (14,19)
		AND FORMAT(so.APP_CREATE_TIMESTAMP, 'dd-MM-yyyy') <= '07-MAY-2020'
)

DELETE HMR_WILDLIFE_REPORT_HIST

WHERE EXISTS

(
	SELECT *

	FROM  [dbo].[HMR_SUBMISSION_OBJECT] so

	WHERE so.SUBMISSION_OBJECT_ID = HMR_WILDLIFE_REPORT_HIST.SUBMISSION_OBJECT_ID

		AND so.SERVICE_AREA_NUMBER IN (14,19)
		AND FORMAT(so.APP_CREATE_TIMESTAMP, 'dd-MM-yyyy') <= '07-MAY-2020'
)

DELETE HMR_FEEDBACK_MESSAGE

WHERE EXISTS

(
	SELECT *

	FROM  [dbo].[HMR_SUBMISSION_OBJECT] so

	WHERE so.SUBMISSION_OBJECT_ID = HMR_FEEDBACK_MESSAGE.SUBMISSION_OBJECT_ID

		AND so.SERVICE_AREA_NUMBER IN (14,19)
		AND FORMAT(so.APP_CREATE_TIMESTAMP, 'dd-MM-yyyy') <= '07-MAY-2020'
)


DELETE HMR_SUBMISSION_ROW

WHERE EXISTS

(
	SELECT *

	FROM  [dbo].[HMR_SUBMISSION_OBJECT] so

	WHERE so.SUBMISSION_OBJECT_ID = HMR_SUBMISSION_ROW.SUBMISSION_OBJECT_ID

		AND so.SERVICE_AREA_NUMBER IN (14,19)
		AND FORMAT(so.APP_CREATE_TIMESTAMP, 'dd-MM-yyyy') <= '07-MAY-2020'
)

DELETE HMR_SUBMISSION_ROW_HIST

WHERE EXISTS

(
	SELECT *

	FROM  [dbo].[HMR_SUBMISSION_OBJECT] so

	WHERE so.SUBMISSION_OBJECT_ID = HMR_SUBMISSION_ROW_HIST.SUBMISSION_OBJECT_ID

		AND so.SERVICE_AREA_NUMBER IN (14,19)
		AND FORMAT(so.APP_CREATE_TIMESTAMP, 'dd-MM-yyyy') <= '07-MAY-2020'
)

DELETE HMR_SUBMISSION_OBJECT

		WHERE
			SERVICE_AREA_NUMBER IN (14,19)
			AND FORMAT(APP_CREATE_TIMESTAMP, 'dd-MM-yyyy') <= '07-MAY-2020'