USE HMR_DEV; -- uncomment appropriate instance
--USE HMR_TST;
--USE HMR_UAT;
--USE HMR_PRD;
GO

/* logically delete un-used/obsolete rules */
UPDATE HMR_ACTIVITY_CODE_RULE 
SET END_DATE = GETDATE()
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_KM_NONPAVED' AND DISPLAY_ORDER = 6) + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_KM_NONPAVED' AND DISPLAY_ORDER = 6;

UPDATE HMR_ACTIVITY_CODE_RULE 
SET END_DATE = GETDATE()
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_KM_20' AND DISPLAY_ORDER = 8) + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_KM_20' AND DISPLAY_ORDER = 8;

UPDATE HMR_ACTIVITY_CODE_RULE
SET END_DATE = GETDATE()
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'ALL_CLASSES' AND ACTIVITY_RULE_SET = 'ROAD_CLASS') + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'ALL_CLASSES' AND ACTIVITY_RULE_SET = 'ROAD_CLASS';

/* update rule name and exec name */
UPDATE HMR_ACTIVITY_CODE_RULE
SET ACTIVITY_RULE_NAME = '[Qty] ≤ [2.0] * [Road KM * 1000] * [3.5]'
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'RATE_LANE_KM_35' AND DISPLAY_ORDER = 3) + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'RATE_LANE_KM_35' AND DISPLAY_ORDER = 3;

UPDATE HMR_ACTIVITY_CODE_RULE
SET ACTIVITY_RULE_NAME = '[Qty] ≤ [3.0] * [Road KM * 1000] * [6.0]'
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'RATE_LANE_KM_60' AND DISPLAY_ORDER = 4) + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'RATE_LANE_KM_60' AND DISPLAY_ORDER = 4;

UPDATE HMR_ACTIVITY_CODE_RULE
SET ACTIVITY_RULE_NAME = '[Qty] ≤ [Lane KM] * 2.0', ACTIVITY_RULE_EXEC_NAME = 'LANE_KM_20'
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'LANE_KM_PAVED_20' AND DISPLAY_ORDER = 7) + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'LANE_KM_PAVED_20' AND DISPLAY_ORDER = 7;

UPDATE HMR_ACTIVITY_CODE_RULE
SET ACTIVITY_RULE_NAME = '[Qty] ≤ [Guardrail Length * 1000.0]', ACTIVITY_RULE_EXEC_NAME = 'GUARDRAIL_LEN_METERS'
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'BARRIER_LEN_METERS' AND DISPLAY_ORDER = 15) + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'BARRIER_LEN_METERS' AND DISPLAY_ORDER = 15;

/* adjust display order or road length rules */
UPDATE HMR_ACTIVITY_CODE_RULE
SET DISPLAY_ORDER = 6
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'LANE_KM') + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'LANE_KM';

UPDATE HMR_ACTIVITY_CODE_RULE
SET DISPLAY_ORDER = 7
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'LANE_KM_20') + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'LANE_KM_20';

UPDATE HMR_ACTIVITY_CODE_RULE
SET DISPLAY_ORDER = 8
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'LANE_METERS') + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'LANE_METERS';

UPDATE HMR_ACTIVITY_CODE_RULE
SET DISPLAY_ORDER = 9
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_KM') + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_KM';

UPDATE HMR_ACTIVITY_CODE_RULE
SET DISPLAY_ORDER = 10
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_KM_20' AND END_DATE IS NULL) + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_KM_20' AND END_DATE IS NULL;

UPDATE HMR_ACTIVITY_CODE_RULE
SET DISPLAY_ORDER = 11
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_METERS') + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_METERS';

UPDATE HMR_ACTIVITY_CODE_RULE
SET DISPLAY_ORDER = 12
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_METERS_20') + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_METERS_20';

UPDATE HMR_ACTIVITY_CODE_RULE
SET DISPLAY_ORDER = 13
, CONCURRENCY_CONTROL_NUMBER = (SELECT CONCURRENCY_CONTROL_NUMBER 
								FROM HMR_ACTIVITY_CODE_RULE 
								WHERE ACTIVITY_RULE_EXEC_NAME = 'GUARDRAIL_LEN_METERS') + 1
WHERE ACTIVITY_RULE_EXEC_NAME = 'GUARDRAIL_LEN_METERS';
