/* ---------------------------------------------------------------------- */
/* Script generated with: DeZign for Databases 11.1.0                     */
/* Target DBMS:           MS SQL Server 2017                              */
/* Project file:          APP_HMR.dez                                     */
/* Project name:          Highway Maintenance Reporting                   */
/* Author:                Ayodeji Kuponiyi                                */
/* Script type:           Alter database script                           */
/* Created on:            2020-03-25 00:55                                */
/* ---------------------------------------------------------------------- */

USE HMR_DEV;
/*
Major updates:
	i)		included contract_term_id in submission_object as a FK
	ii)		increased the length of Highway Unique Name from 40 to 255 on Wildlife_Report and Wildlife_Report_Hist tables
*/


/* ---------------------------------------------------------------------- */
/* Drop triggers                                                          */
/* ---------------------------------------------------------------------- */

GO


DROP TRIGGER [dbo].[HMR_SUBM_OBJ_I_S_I_TR]
GO


DROP TRIGGER [dbo].[HMR_SUBM_OBJ_I_S_U_TR]
GO


DROP TRIGGER [dbo].[HMR_WLDLF_RPT_I_S_I_TR]
GO


/* ---------------------------------------------------------------------- */
/* Drop foreign key constraints                                           */
/* ---------------------------------------------------------------------- */

GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] DROP CONSTRAINT [HRM_SUBM_OBJ_MIME_TYPE_FK]
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] DROP CONSTRAINT [HRM_SUBM_OBJ_SRV_AREA_FK]
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] DROP CONSTRAINT [HRM_SUBM_OBJ_SUBM_STAT_CODE_FK]
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] DROP CONSTRAINT [HMR_SUBM_OBJ_PRTY_FK]
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] DROP CONSTRAINT [HMR_SUBM_OBJ_SUBM_STR_FK]
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] DROP CONSTRAINT [HMR_WLDLF_RPT_HMR_SRV_ARA_FK]
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] DROP CONSTRAINT [HMR_WLDLF_RPT_SUBM_OBJ_FK]
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] DROP CONSTRAINT [HMR_WLDLF_RRT_SUBM_STAT_FK]
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] DROP CONSTRAINT [HMR_WLDLF_RRT_SUBM_RW_FK]
GO


ALTER TABLE [dbo].[HMR_FEEDBACK_MESSAGE] DROP CONSTRAINT [HMR_FDBK_MSG_SUBM_OBJ_FK]
GO


ALTER TABLE [dbo].[HMR_ROCKFALL_REPORT] DROP CONSTRAINT [HMR_RCKFL_RPT_SUBM_OBJ_FK]
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_ROW] DROP CONSTRAINT [HMR_SUBM_RW_HMR_SUBM_OBJ_FK]
GO


ALTER TABLE [dbo].[HMR_WORK_REPORT] DROP CONSTRAINT [HMR_WRK_RRT_SUBM_OBJ_FK]
GO


/* ---------------------------------------------------------------------- */
/* Drop and recreate table "dbo.HMR_SUBMISSION_OBJECT"                    */
/* ---------------------------------------------------------------------- */

GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] DROP CONSTRAINT [HMR_SUBM_OBJ_PK]
GO


CREATE TABLE [dbo].[HMR_SUBMISSION_OBJECT_TMP] (
    [SUBMISSION_OBJECT_ID] NUMERIC(9) DEFAULT NEXT VALUE FOR [HMR_SUBM_OBJ_ID_SEQ] NOT NULL,
    [FILE_NAME] VARCHAR(100) NOT NULL,
    [DIGITAL_REPRESENTATION] VARBINARY(max) NOT NULL,
    [MIME_TYPE_ID] NUMERIC(9) DEFAULT 0 NOT NULL,
    [CONTRACT_TERM_ID] NUMERIC(9),
    [SUBMISSION_STATUS_ID] NUMERIC(9) NOT NULL,
    [SERVICE_AREA_NUMBER] NUMERIC(9) NOT NULL,
    [PARTY_ID] NUMERIC(9),
    [FILE_HASH] VARCHAR(256),
    [ERROR_DETAIL] VARCHAR(4000),
    [SUBMISSION_STREAM_ID] NUMERIC(9) NOT NULL,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT DEFAULT 1 NOT NULL,
    [APP_CREATE_USERID] VARCHAR(30) NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [APP_CREATE_USER_DIRECTORY] VARCHAR(12) NOT NULL,
    [APP_LAST_UPDATE_USERID] VARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [APP_LAST_UPDATE_USER_DIRECTORY] VARCHAR(12) NOT NULL,
    [DB_AUDIT_CREATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_CREATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL)
GO

--modified the insert to accomodate the addition of contract_term_id to submission_object by pulling contract_term_ids from the contract_term table through the party_id (in party table)
INSERT INTO [dbo].[HMR_SUBMISSION_OBJECT_TMP]
    ([SUBMISSION_OBJECT_ID],[FILE_NAME],[DIGITAL_REPRESENTATION],[MIME_TYPE_ID],[CONTRACT_TERM_ID],[SUBMISSION_STATUS_ID],[SERVICE_AREA_NUMBER],[PARTY_ID],[FILE_HASH],[ERROR_DETAIL],[SUBMISSION_STREAM_ID],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_CREATE_USER_DIRECTORY],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[APP_LAST_UPDATE_USER_DIRECTORY],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP])
--SELECT
--    hso.[SUBMISSION_OBJECT_ID],hso.[FILE_NAME],hso.[DIGITAL_REPRESENTATION],hso.[MIME_TYPE_ID],hct.[CONTRACT_TERM_ID],hso.[SUBMISSION_STATUS_ID],hso.[SERVICE_AREA_NUMBER],hso.[PARTY_ID],hso.[FILE_HASH],hso.[ERROR_DETAIL],hso.[SUBMISSION_STREAM_ID],hso.[CONCURRENCY_CONTROL_NUMBER],hso.[APP_CREATE_USERID],hso.[APP_CREATE_TIMESTAMP],hso.[APP_CREATE_USER_GUID],hso.[APP_CREATE_USER_DIRECTORY],hso.[APP_LAST_UPDATE_USERID],hso.[APP_LAST_UPDATE_TIMESTAMP],hso.[APP_LAST_UPDATE_USER_GUID],hso.[APP_LAST_UPDATE_USER_DIRECTORY],hso.[DB_AUDIT_CREATE_USERID],hso.[DB_AUDIT_CREATE_TIMESTAMP],hso.[DB_AUDIT_LAST_UPDATE_USERID],hso.[DB_AUDIT_LAST_UPDATE_TIMESTAMP]
--FROM [dbo].[HMR_SUBMISSION_OBJECT] AS hso LEFT JOIN [dbo].[HMR_PARTY] AS hpi ON (hso.PARTY_ID = hpi.PARTY_ID) LEFT JOIN [dbo].[HMR_CONTRACT_TERM] AS hct ON (hpi.PARTY_ID = hct.PARTY_ID)
SELECT
hso.[SUBMISSION_OBJECT_ID],
hso.[FILE_NAME],
hso.[DIGITAL_REPRESENTATION],
hso.[MIME_TYPE_ID],
hct.[CONTRACT_TERM_ID],
hso.[SUBMISSION_STATUS_ID],
hso.[SERVICE_AREA_NUMBER],
hso.[PARTY_ID],
hso.[FILE_HASH],
hso.[ERROR_DETAIL],hso.[SUBMISSION_STREAM_ID],hso.[CONCURRENCY_CONTROL_NUMBER],hso.[APP_CREATE_USERID],hso.[APP_CREATE_TIMESTAMP],hso.[APP_CREATE_USER_GUID],hso.[APP_CREATE_USER_DIRECTORY],hso.[APP_LAST_UPDATE_USERID],hso.[APP_LAST_UPDATE_TIMESTAMP],hso.[APP_LAST_UPDATE_USER_GUID],hso.[APP_LAST_UPDATE_USER_DIRECTORY],hso.[DB_AUDIT_CREATE_USERID],hso.[DB_AUDIT_CREATE_TIMESTAMP],hso.[DB_AUDIT_LAST_UPDATE_USERID],hso.[DB_AUDIT_LAST_UPDATE_TIMESTAMP]
FROM [dbo].[HMR_SUBMISSION_OBJECT] AS hso 
LEFT JOIN [dbo].[HMR_PARTY] AS hpi ON (hso.PARTY_ID = hpi.PARTY_ID) 
LEFT JOIN [dbo].[HMR_CONTRACT_TERM] AS hct ON hso.SERVICE_AREA_NUMBER = hct.SERVICE_AREA_NUMBER
WHERE getdate() BETWEEN hct.START_DATE AND hct.END_DATE

GO


DROP INDEX [dbo].[HMR_SUBMISSION_OBJECT].[HMR_SUBM_OBJ_FK_I]
GO


DROP TABLE [dbo].[HMR_SUBMISSION_OBJECT]
GO


EXEC sp_rename '[dbo].[HMR_SUBMISSION_OBJECT_TMP]', 'HMR_SUBMISSION_OBJECT', 'OBJECT'
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] ADD CONSTRAINT [HMR_SUBM_OBJ_PK] 
    PRIMARY KEY CLUSTERED ([SUBMISSION_OBJECT_ID])
GO


CREATE NONCLUSTERED INDEX [HMR_SUBM_OBJ_FK_I] ON [dbo].[HMR_SUBMISSION_OBJECT] ([SUBMISSION_STATUS_ID] ASC,[SERVICE_AREA_NUMBER] ASC,[SUBMISSION_STREAM_ID] ASC)
GO


EXECUTE sp_addextendedproperty N'MS_Description', N'Unique identifier for CONTRACT TERM', 'SCHEMA', N'dbo', 'TABLE', N'HMR_SUBMISSION_OBJECT', 'COLUMN', N'CONTRACT_TERM_ID'
GO


/* ---------------------------------------------------------------------- */
/* Alter table "dbo.HMR_WILDLIFE_REPORT"                                  */
/* ---------------------------------------------------------------------- */

GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] ALTER COLUMN [HIGHWAY_UNIQUE_NAME] VARCHAR(255)
GO


EXECUTE sp_updateextendedproperty N'MS_Description', N'This identifies the section of road on which the incident occurred. This is a value in the in the format: [Service Area]-[area manager area]-[subarea]-[highway number] This reference number reflects a valid reference in the road network (currenltyRFI within  CHRIS as of 2019)', 'SCHEMA', N'dbo', 'TABLE', N'HMR_WILDLIFE_REPORT', 'COLUMN', N'HIGHWAY_UNIQUE'
GO


EXECUTE sp_updateextendedproperty N'MS_Description', N'This field is needed for linear referencing for location specific reports.  Offset from beginning of segment.', 'SCHEMA', N'dbo', 'TABLE', N'HMR_WILDLIFE_REPORT', 'COLUMN', N'OFFSET'
GO


/* ---------------------------------------------------------------------- */
/* Alter table "dbo.HMR_WILDLIFE_REPORT_HIST"                             */
/* ---------------------------------------------------------------------- */

GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT_HIST] ALTER COLUMN [HIGHWAY_UNIQUE_NAME] VARCHAR(255)
GO


/* ---------------------------------------------------------------------- */
/* Add foreign key constraints                                            */
/* ---------------------------------------------------------------------- */

GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] ADD CONSTRAINT [HRM_SUBM_OBJ_MIME_TYPE_FK] 
    FOREIGN KEY ([MIME_TYPE_ID]) REFERENCES [dbo].[HMR_MIME_TYPE] ([MIME_TYPE_ID])
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] ADD CONSTRAINT [HRM_SUBM_OBJ_SRV_AREA_FK] 
    FOREIGN KEY ([SERVICE_AREA_NUMBER]) REFERENCES [dbo].[HMR_SERVICE_AREA] ([SERVICE_AREA_NUMBER])
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] ADD CONSTRAINT [HRM_SUBM_OBJ_SUBM_STAT_CODE_FK] 
    FOREIGN KEY ([SUBMISSION_STATUS_ID]) REFERENCES [dbo].[HMR_SUBMISSION_STATUS] ([STATUS_ID])
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] ADD CONSTRAINT [HMR_SUBM_OBJ_PRTY_FK] 
    FOREIGN KEY ([PARTY_ID]) REFERENCES [dbo].[HMR_PARTY] ([PARTY_ID])
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] ADD CONSTRAINT [HMR_SUBM_OBJ_SUBM_STR_FK] 
    FOREIGN KEY ([SUBMISSION_STREAM_ID]) REFERENCES [dbo].[HMR_SUBMISSION_STREAM] ([SUBMISSION_STREAM_ID])
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_OBJECT] ADD CONSTRAINT [HMR_SUBM_OBJ_CNT_TRM_FK]		--changed the format from HMR_CONTRACT_TERM_HMR_SUBMISSION_OBJECT 
    FOREIGN KEY ([CONTRACT_TERM_ID]) REFERENCES [dbo].[HMR_CONTRACT_TERM] ([CONTRACT_TERM_ID])
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] ADD CONSTRAINT [HMR_WLDLF_RPT_HMR_SRV_ARA_FK] 
    FOREIGN KEY ([SERVICE_AREA]) REFERENCES [dbo].[HMR_SERVICE_AREA] ([SERVICE_AREA_NUMBER])
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] ADD CONSTRAINT [HMR_WLDLF_RPT_SUBM_OBJ_FK] 
    FOREIGN KEY ([SUBMISSION_OBJECT_ID]) REFERENCES [dbo].[HMR_SUBMISSION_OBJECT] ([SUBMISSION_OBJECT_ID])
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] ADD CONSTRAINT [HMR_WLDLF_RRT_SUBM_STAT_FK] 
    FOREIGN KEY ([VALIDATION_STATUS_ID]) REFERENCES [dbo].[HMR_SUBMISSION_STATUS] ([STATUS_ID])
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] ADD CONSTRAINT [HMR_WLDLF_RRT_SUBM_RW_FK] 
    FOREIGN KEY ([ROW_ID]) REFERENCES [dbo].[HMR_SUBMISSION_ROW] ([ROW_ID])
GO


ALTER TABLE [dbo].[HMR_FEEDBACK_MESSAGE] ADD CONSTRAINT [HMR_FDBK_MSG_SUBM_OBJ_FK] 
    FOREIGN KEY ([SUBMISSION_OBJECT_ID]) REFERENCES [dbo].[HMR_SUBMISSION_OBJECT] ([SUBMISSION_OBJECT_ID])
GO


ALTER TABLE [dbo].[HMR_ROCKFALL_REPORT] ADD CONSTRAINT [HMR_RCKFL_RPT_SUBM_OBJ_FK] 
    FOREIGN KEY ([SUBMISSION_OBJECT_ID]) REFERENCES [dbo].[HMR_SUBMISSION_OBJECT] ([SUBMISSION_OBJECT_ID])
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_ROW] ADD CONSTRAINT [HMR_SUBM_RW_HMR_SUBM_OBJ_FK] 
    FOREIGN KEY ([SUBMISSION_OBJECT_ID]) REFERENCES [dbo].[HMR_SUBMISSION_OBJECT] ([SUBMISSION_OBJECT_ID])
GO


ALTER TABLE [dbo].[HMR_WORK_REPORT] ADD CONSTRAINT [HMR_WRK_RRT_SUBM_OBJ_FK] 
    FOREIGN KEY ([SUBMISSION_OBJECT_ID]) REFERENCES [dbo].[HMR_SUBMISSION_OBJECT] ([SUBMISSION_OBJECT_ID])
GO


/* ---------------------------------------------------------------------- */
/* Repair/add triggers                                                    */
/* ---------------------------------------------------------------------- */

GO


CREATE TRIGGER [dbo].[HMR_SUBM_OBJ_I_S_I_TR] ON HMR_SUBMISSION_OBJECT INSTEAD OF INSERT AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM inserted)
    RETURN;


  insert into HMR_SUBMISSION_OBJECT ("SUBMISSION_OBJECT_ID",
      "FILE_NAME",
      "DIGITAL_REPRESENTATION",
      "MIME_TYPE_ID",
      "CONTRACT_TERM_ID",
      "SUBMISSION_STATUS_ID",
      "SERVICE_AREA_NUMBER",
      "PARTY_ID",
      "FILE_HASH",
      "ERROR_DETAIL",
      "SUBMISSION_STREAM_ID",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_USERID",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USER_GUID",
      "APP_CREATE_USER_DIRECTORY",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY")
    select "SUBMISSION_OBJECT_ID",
      "FILE_NAME",
      "DIGITAL_REPRESENTATION",
      "MIME_TYPE_ID",
      "CONTRACT_TERM_ID",
      "SUBMISSION_STATUS_ID",
      "SERVICE_AREA_NUMBER",
      "PARTY_ID",
      "FILE_HASH",
      "ERROR_DETAIL",
      "SUBMISSION_STREAM_ID",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_USERID",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USER_GUID",
      "APP_CREATE_USER_DIRECTORY",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY"
    from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC hmr_error_handling
END CATCH;
GO


CREATE TRIGGER [dbo].[HMR_SUBM_OBJ_I_S_U_TR] ON HMR_SUBMISSION_OBJECT INSTEAD OF UPDATE AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM deleted)
    RETURN;

  -- validate concurrency control
  if exists (select 1 from inserted, deleted where inserted.CONCURRENCY_CONTROL_NUMBER != deleted.CONCURRENCY_CONTROL_NUMBER+1 AND inserted.SUBMISSION_OBJECT_ID = deleted.SUBMISSION_OBJECT_ID)
    raiserror('CONCURRENCY FAILURE.',16,1)


  -- update statement
  update HMR_SUBMISSION_OBJECT
    set "SUBMISSION_OBJECT_ID" = inserted."SUBMISSION_OBJECT_ID",
      "FILE_NAME" = inserted."FILE_NAME",
      "DIGITAL_REPRESENTATION" = inserted."DIGITAL_REPRESENTATION",
      "MIME_TYPE_ID" = inserted."MIME_TYPE_ID",
      "CONTRACT_TERM_ID" = inserted."CONTRACT_TERM_ID",
      "SUBMISSION_STATUS_ID" = inserted."SUBMISSION_STATUS_ID",
      "SERVICE_AREA_NUMBER" = inserted."SERVICE_AREA_NUMBER",
      "PARTY_ID" = inserted."PARTY_ID",
      "FILE_HASH" = inserted."FILE_HASH",
      "ERROR_DETAIL" = inserted."ERROR_DETAIL",
      "SUBMISSION_STREAM_ID" = inserted."SUBMISSION_STREAM_ID",
      "CONCURRENCY_CONTROL_NUMBER" = inserted."CONCURRENCY_CONTROL_NUMBER",
      "APP_LAST_UPDATE_USERID" = inserted."APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_TIMESTAMP" = inserted."APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USER_GUID" = inserted."APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY" = inserted."APP_LAST_UPDATE_USER_DIRECTORY"
    , DB_AUDIT_LAST_UPDATE_TIMESTAMP = getutcdate()
    , DB_AUDIT_LAST_UPDATE_USERID = user_name()
    from HMR_SUBMISSION_OBJECT
    inner join inserted
    on (HMR_SUBMISSION_OBJECT.SUBMISSION_OBJECT_ID = inserted.SUBMISSION_OBJECT_ID);

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC hmr_error_handling
END CATCH;
GO


CREATE TRIGGER [dbo].[HMR_WLDLF_RPT_I_S_I_TR] ON HMR_WILDLIFE_REPORT INSTEAD OF INSERT AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM inserted)
    RETURN;


  insert into HMR_WILDLIFE_REPORT ("WILDLIFE_RECORD_ID",
      "SUBMISSION_OBJECT_ID", 
      "ROW_ID",
      "ROW_NUM",
      "VALIDATION_STATUS_ID",
      "RECORD_TYPE",
      "SERVICE_AREA",
      "ACCIDENT_DATE",
      "TIME_OF_KILL",
      "LATITUDE",
      "LONGITUDE",
      "HIGHWAY_UNIQUE",
      "HIGHWAY_UNIQUE_NAME",
      "HIGHWAY_UNIQUE_LENGTH",
      "LANDMARK",
      "OFFSET",
      "NEAREST_TOWN",
      "WILDLIFE_SIGN",
      "QUANTITY",
      "SPECIES",
      "SEX",
      "AGE",
      "COMMENT",
      "GEOMETRY",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_USERID",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USER_GUID",
      "APP_CREATE_USER_DIRECTORY",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY")
    select "WILDLIFE_RECORD_ID",
      "SUBMISSION_OBJECT_ID", 
      "ROW_ID",
      "ROW_NUM",
      "VALIDATION_STATUS_ID",
      "RECORD_TYPE",
      "SERVICE_AREA",
      "ACCIDENT_DATE",
      "TIME_OF_KILL",
      "LATITUDE",
      "LONGITUDE",
      "HIGHWAY_UNIQUE",
      "HIGHWAY_UNIQUE_NAME",
      "HIGHWAY_UNIQUE_LENGTH",
      "LANDMARK",
      "OFFSET",
      "NEAREST_TOWN",
      "WILDLIFE_SIGN",
      "QUANTITY",
      "SPECIES",
      "SEX",
      "AGE",
      "COMMENT",
      "GEOMETRY",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_USERID",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USER_GUID",
      "APP_CREATE_USER_DIRECTORY",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY"
    from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC hmr_error_handling
END CATCH;
GO

