-- =============================================
-- Author:		Ben Driver
-- Create date: 2020-03-02
-- Updates: 
--	
-- 
-- Description:	
--  - Role creation for APPLICATION_PROXY role
-- =============================================

USE HMR_DEV; -- uncomment appropriate instance
--USE HMR_TST;
--USE HMR_UAT;
--USE HMR_PRD;
GO

-- Create ROLE

if not exists (select 1 from sys.database_principals where name='HMR_APPLICATION_PROXY' and Type = 'R')
	begin
		CREATE ROLE HMR_APPLICATION_PROXY AUTHORIZATION db_securityadmin;
	end
GO

GRANT select ON dbo.HMR_ACTIVITY_CODE TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_ACTIVITY_CODE_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_CODE_LOOKUP TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_CODE_LOOKUP_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_CONTRACT_TERM TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_CONTRACT_TERM_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_DISTRICT TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_FEEDBACK_MESSAGE TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_LOCATION_CODE TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_LOCATION_CODE_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_MIME_TYPE TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_PARTY TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_PARTY_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_PERMISSION TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_PERMISSION_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_REGION TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_ROCKFALL_REPORT TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_ROCKFALL_REPORT_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_ROLE TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_ROLE_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_ROLE_PERMISSION TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_ROLE_PERMISSION_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SERVICE_AREA TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SERVICE_AREA_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SERVICE_AREA_USER TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SERVICE_AREA_USER_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_STREAM_ELEMENT TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_STREAM_ELEMENT_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SUBMISSION_OBJECT TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SUBMISSION_ROW TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SUBMISSION_ROW_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SUBMISSION_STATUS TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SUBMISSION_STREAM TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SUBMISSION_STREAM_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SYSTEM_USER TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SYSTEM_USER_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_SYSTEM_VALIDATION TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_USER_ROLE TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_USER_ROLE_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_WILDLIFE_REPORT TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_WILDLIFE_REPORT_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_WORK_REPORT TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_WORK_REPORT_HIST TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_ROCKFALL_REPORT_VW TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_WILDLIFE_REPORT_VW TO HMR_APPLICATION_PROXY;
GRANT select ON dbo.HMR_WORK_REPORT_VW TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_ACTIVITY_CODE TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_ACTIVITY_CODE_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_CODE_LOOKUP TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_CODE_LOOKUP_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_CONTRACT_TERM TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_CONTRACT_TERM_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_DISTRICT TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_FEEDBACK_MESSAGE TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_LOCATION_CODE TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_LOCATION_CODE_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_MIME_TYPE TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_PARTY TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_PARTY_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_PERMISSION TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_PERMISSION_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_REGION TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_ROCKFALL_REPORT TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_ROCKFALL_REPORT_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_ROLE TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_ROLE_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_ROLE_PERMISSION TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_ROLE_PERMISSION_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SERVICE_AREA TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SERVICE_AREA_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SERVICE_AREA_USER TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SERVICE_AREA_USER_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_STREAM_ELEMENT TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_STREAM_ELEMENT_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SUBMISSION_OBJECT TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SUBMISSION_ROW TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SUBMISSION_ROW_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SUBMISSION_STATUS TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SUBMISSION_STREAM TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SUBMISSION_STREAM_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SYSTEM_USER TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SYSTEM_USER_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_SYSTEM_VALIDATION TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_USER_ROLE TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_USER_ROLE_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_WILDLIFE_REPORT TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_WILDLIFE_REPORT_HIST TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_WORK_REPORT TO HMR_APPLICATION_PROXY;
GRANT insert, update ON dbo.HMR_WORK_REPORT_HIST TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_ACTIVITY_CODE TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_CODE_LOOKUP TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_CONTRACT_TERM TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_DISTRICT TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_FEEDBACK_MESSAGE TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_LOCATION_CODE TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_MIME_TYPE TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_PARTY TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_PERMISSION TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_REGION TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_ROCKFALL_REPORT TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_ROLE TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_ROLE_PERMISSION TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_SERVICE_AREA TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_SERVICE_AREA_USER TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_STREAM_ELEMENT TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_SUBMISSION_OBJECT TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_SUBMISSION_ROW TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_SUBMISSION_STATUS TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_SUBMISSION_STREAM TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_SYSTEM_USER TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_SYSTEM_VALIDATION TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_USER_ROLE TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_WILDLIFE_REPORT TO HMR_APPLICATION_PROXY;
GRANT delete ON dbo.HMR_WORK_REPORT TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.FDBK_MSG_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_ACT_CODE_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_ACTIVITY_CODE_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_CNT_TRM_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_CODE_LKUP_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_CODE_LOOKUP_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_CONTRACT_TERM_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_DIST_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_LOC_CODE_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_LOCATION_CODE_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_MIME_TYPE_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_PARTY_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_PERM_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_PERMISSION_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_PRTY_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_RCKF_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_REG_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_RL_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_RL_PERM_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_ROCKFALL_REPORT_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_ROLE_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_ROLE_PERMISSION_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_SERVICE_AREA_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_SERVICE_AREA_USER_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_SRV_ARA_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_SRV_AREA_USR_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_STR_ELMT_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_STREAM_ELEMENT_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_SUBM_OBJ_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_SUBM_RW_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_SUBM_STAT_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_SUBM_STR_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_SUBMISSION_ROW_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_SUBMISSION_STREAM_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_SYSTEM_USER_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_USER_ROLE_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_USR_RL_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_WILDLIFE_REPORT_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_WLDLF_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_WORK_REPORT_H_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.HMR_WRK_RPT_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.SYS_USR_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT update ON dbo.SYS_VLD_ID_SEQ TO HMR_APPLICATION_PROXY;
GRANT execute ON dbo.hmr_error_handling TO HMR_APPLICATION_PROXY;

GO
