USE HMR_DEV; -- uncomment appropriate instance
--USE HMR_TST;
--USE HMR_UAT;
--USE HMR_PRD;
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   ACTIVITY_RULE_NAME = N'[Qty]  ≤ [0.120] * [Lane KM * 1000.0] * 3.5',
       ACTIVITY_RULE_EXEC_NAME = 'RATE_LANE_KM_TONNES1'
 WHERE ACTIVITY_RULE_EXEC_NAME = 'RATE_LANE_KM'
GO

INSERT INTO [dbo].[HMR_ACTIVITY_CODE_RULE]
    ([ACTIVITY_RULE_SET],[ACTIVITY_RULE_NAME],[ACTIVITY_RULE_EXEC_NAME],[DISPLAY_ORDER], [END_DATE])
VALUES
    ('ROAD_LENGTH', N'[Qty] ≤ [0.146] * [Lane KM * 1000.0] * 3.5', 'RATE_LANE_KM_TONNES2', 3, NULL)
GO

INSERT INTO [dbo].[HMR_ACTIVITY_CODE_RULE]
    ([ACTIVITY_RULE_SET],[ACTIVITY_RULE_NAME],[ACTIVITY_RULE_EXEC_NAME],[DISPLAY_ORDER], [END_DATE])
VALUES
    ('ROAD_LENGTH', N'[Qty] ≤ [1.1] * [Lane KM * 1000.0] * 3.5', 'RATE_LANE_KM_LITRES1', 4, NULL)
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   DISPLAY_ORDER = 5,
      ACTIVITY_RULE_NAME = N'[Qty] ≤ [2.0] * [Road KM * 1000] * [3.5]'
 WHERE ACTIVITY_RULE_EXEC_NAME = 'RATE_LANE_KM_35'
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   DISPLAY_ORDER = 6,
      ACTIVITY_RULE_NAME = N'[Qty] ≤ [3.0] * [Road KM * 1000] * [6.0]'
 WHERE ACTIVITY_RULE_EXEC_NAME = 'RATE_LANE_KM_60'
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   DISPLAY_ORDER = 7
 WHERE ACTIVITY_RULE_EXEC_NAME = 'LANE_METERS_35'
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   DISPLAY_ORDER = 8
 WHERE ACTIVITY_RULE_EXEC_NAME = 'LANE_KM'
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   DISPLAY_ORDER = 9,
      ACTIVITY_RULE_NAME = N'[Qty] ≤ [Lane KM] * 2.0'
 WHERE ACTIVITY_RULE_EXEC_NAME = 'LANE_KM_20'
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   DISPLAY_ORDER = 10
 WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_KM_20'
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   DISPLAY_ORDER = 10
 WHERE ACTIVITY_RULE_EXEC_NAME = 'LANE_METERS'
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   DISPLAY_ORDER = 11
 WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_KM'
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   DISPLAY_ORDER = 12
 WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_KM_20'
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   DISPLAY_ORDER = 13
 WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_METERS'
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   DISPLAY_ORDER = 14
 WHERE ACTIVITY_RULE_EXEC_NAME = 'ROAD_METERS_20'
GO

UPDATE HMR_ACTIVITY_CODE_RULE 
   SET CONCURRENCY_CONTROL_NUMBER = CONCURRENCY_CONTROL_NUMBER + 1,
	   DISPLAY_ORDER = 15,
      ACTIVITY_RULE_NAME = N'[Qty] ≤ [Guardrail Length * 1000.0]'
 WHERE ACTIVITY_RULE_EXEC_NAME = 'GUARDRAIL_LEN_METERS'
GO