-- =============================================
-- Author:		Ben Driver
-- Create date: 2020-03-02
-- Updates: 
--	
-- 
-- Description:	
--  - Role creation for READ_ONLY role
-- =============================================

USE HMR_DEV; -- uncomment appropriate instance
--USE HMR_TST;
--USE HMR_UAT;
--USE HMR_PRD;
GO

-- Create ROLE

if not exists (select 1 from sys.database_principals where name='HMR_READ_ONLY' and Type = 'R')
	begin
		CREATE ROLE HMR_READ_ONLY AUTHORIZATION db_securityadmin;
	end

-- GRANT select on tables

GRANT select ON dbo.HMR_ACTIVITY_CODE TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_ACTIVITY_CODE_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_CODE_LOOKUP TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_CODE_LOOKUP_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_CONTRACT_TERM TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_CONTRACT_TERM_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_DISTRICT TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_FEEDBACK_MESSAGE TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_LOCATION_CODE TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_LOCATION_CODE_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_MIME_TYPE TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_PARTY TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_PARTY_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_PERMISSION TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_PERMISSION_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_REGION TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_ROCKFALL_REPORT TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_ROCKFALL_REPORT_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_ROLE TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_ROLE_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_ROLE_PERMISSION TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_ROLE_PERMISSION_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SERVICE_AREA TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SERVICE_AREA_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SERVICE_AREA_USER TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SERVICE_AREA_USER_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_STREAM_ELEMENT TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_STREAM_ELEMENT_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SUBMISSION_OBJECT TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SUBMISSION_ROW TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SUBMISSION_ROW_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SUBMISSION_STATUS TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SUBMISSION_STREAM TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SUBMISSION_STREAM_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SYSTEM_USER TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SYSTEM_USER_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_SYSTEM_VALIDATION TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_USER_ROLE TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_USER_ROLE_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_WILDLIFE_REPORT TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_WILDLIFE_REPORT_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_WORK_REPORT TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_WORK_REPORT_HIST TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_ROCKFALL_REPORT_VW TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_WILDLIFE_REPORT_VW TO HMR_READ_ONLY;
GRANT select ON dbo.HMR_WORK_REPORT_VW TO HMR_READ_ONLY;

GO

