

-- =============================================
-- Author:		Ben Driver
-- Create date: 2020-02-13
-- Updates: 
--	
-- 
-- Description:	Incremnetal DML in support of sprint 5.
--  - Revise stream element attributes for new Rockfall attributes
-- 
-- =============================================

USE HMR_DEV; -- uncomment appropriate instance
--USE HMR_TST;
--USE HMR_UAT;
--USE HMR_PRD;
GO

 /* Load user context variables.  Redeclared for subsequent executions as required */  
	DECLARE @utcdate DATETIME = (SELECT getutcdate() AS utcdate)  
	DECLARE @app_guid UNIQUEIDENTIFIER = (SELECT CASE WHEN SUSER_SID() IS NOT NULL THEN SUSER_SID() ELSE (SELECT CONVERT(uniqueidentifier,STUFF(STUFF(STUFF(STUFF('B00D00A0AC0A0D0C00DD00F0D0C00000',9,0,'-'),14,0,'-'),19,0,'-'),24,0,'-'))) END AS  app_guid)  
	DECLARE @app_user VARCHAR(30) = (SELECT CASE WHEN SUBSTRING(SUSER_NAME(),CHARINDEX('\',SUSER_NAME())+1,LEN(SUSER_NAME())) IS NOT NULL THEN SUBSTRING(SUSER_NAME(),CHARINDEX('\',SUSER_NAME())+1,LEN(SUSER_NAME())) ELSE CURRENT_USER END AS app_user)  
	DECLARE @app_user_dir VARCHAR(12) = (SELECT CASE WHEN LEN(SUBSTRING(SUSER_NAME(),0,CHARINDEX('\',SUSER_NAME(),0)))>1 THEN SUBSTRING(SUSER_NAME(),0,CHARINDEX('\',SUSER_NAME(),0)) ELSE 'WIN AUTH' END AS app_user_dir) 

UPDATE [dbo].[HMR_STREAM_ELEMENT] SET ELEMENT_TYPE='String' , CODE_SET='RKFL_RPT_RECORD_TYPE' , IS_REQUIRED=1 , MAX_LENGTH=1 , MIN_LENGTH=1 , CONCURRENCY_CONTROL_NUMBER=CONCURRENCY_CONTROL_NUMBER+1,APP_LAST_UPDATE_USERID=@app_user , APP_LAST_UPDATE_TIMESTAMP=@utcdate , APP_LAST_UPDATE_USER_GUID=@app_guid , APP_LAST_UPDATE_USER_DIRECTORY=@app_user_dir WHERE SUBMISSION_STREAM_ID = (SELECT SUBMISSION_STREAM_ID FROM HMR_SUBMISSION_STREAM WHERE STREAM_NAME = 'Rockfall Reporting') AND STAGING_COLUMN_NAME = 'RECORD_TYPE';

UPDATE [dbo].[HMR_STREAM_ELEMENT] SET ELEMENT_TYPE='Numeric' , CODE_SET=NULL , IS_REQUIRED=1 , MAX_LENGTH=2 , MIN_LENGTH=1 , CONCURRENCY_CONTROL_NUMBER=CONCURRENCY_CONTROL_NUMBER+1,APP_LAST_UPDATE_USERID=@app_user , APP_LAST_UPDATE_TIMESTAMP=@utcdate , APP_LAST_UPDATE_USER_GUID=@app_guid , APP_LAST_UPDATE_USER_DIRECTORY=@app_user_dir WHERE SUBMISSION_STREAM_ID = (SELECT SUBMISSION_STREAM_ID FROM HMR_SUBMISSION_STREAM WHERE STREAM_NAME = 'Rockfall Reporting') AND STAGING_COLUMN_NAME = 'SERVICE_AREA';

UPDATE [dbo].[HMR_STREAM_ELEMENT] SET ELEMENT_TYPE='Numeric' , CODE_SET=NULL , IS_REQUIRED=0 , MAX_LENGTH=6 , MIN_LENGTH=3 , CONCURRENCY_CONTROL_NUMBER=CONCURRENCY_CONTROL_NUMBER+1,APP_LAST_UPDATE_USERID=@app_user , APP_LAST_UPDATE_TIMESTAMP=@utcdate , APP_LAST_UPDATE_USER_GUID=@app_guid , APP_LAST_UPDATE_USER_DIRECTORY=@app_user_dir WHERE SUBMISSION_STREAM_ID = (SELECT SUBMISSION_STREAM_ID FROM HMR_SUBMISSION_STREAM WHERE STREAM_NAME = 'Rockfall Reporting') AND STAGING_COLUMN_NAME = 'OTHER_DITCH_VOLUME';

UPDATE [dbo].[HMR_STREAM_ELEMENT] SET ELEMENT_TYPE='Numeric' , CODE_SET=NULL , IS_REQUIRED=0 , MAX_LENGTH=6 , MIN_LENGTH=3 , CONCURRENCY_CONTROL_NUMBER=CONCURRENCY_CONTROL_NUMBER+1,APP_LAST_UPDATE_USERID=@app_user , APP_LAST_UPDATE_TIMESTAMP=@utcdate , APP_LAST_UPDATE_USER_GUID=@app_guid , APP_LAST_UPDATE_USER_DIRECTORY=@app_user_dir WHERE SUBMISSION_STREAM_ID = (SELECT SUBMISSION_STREAM_ID FROM HMR_SUBMISSION_STREAM WHERE STREAM_NAME = 'Rockfall Reporting') AND STAGING_COLUMN_NAME = 'OTHER_TRAVELLED_LANES_VOLUME';
GO
