apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: moti-cicd
objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ${NAME}
      namespace: ${PROJECT}-tools
      labels:
        app: ${NAME}
parameters:
  - displayName: Credentials Name
    description: |
      The name used for all components of the 
      credentials.
    name: NAME
    required: true
    value: moti-cicd
  - displayName: Project
    decription: Project
    name: PROJECT
    required: true
