USE HMR_DEV; -- uncomment appropriate instance
--USE HMR_TST;
--USE HMR_UAT;
--USE HMR_PRD;
GO

INSERT INTO [dbo].[HMR_ACTIVITY_CODE_RULE]
           ([ACTIVITY_RULE_SET],[ACTIVITY_RULE_NAME],[ACTIVITY_RULE_EXEC_NAME],[DISPLAY_ORDER])
     VALUES
			('SURFACE_TYPE','GPS Not on Unconstructed','GPS_NOT_UNCONSTRUCTED',5)
GO