/****** Salt Report 2025/26 schema updates ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'SNOW_DISP_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [SNOW_DISP_ID] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'SNOW_DISP_ACH') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [SNOW_DISP_ACH] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'VULN_AREAS_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [VULN_AREAS_ID] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'VULN_AREAS_ACH') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [VULN_AREAS_ACH] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'DEICER_HCOONA') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [DEICER_HCOONA] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'TRTD_ABR_HCOONA') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [TRTD_ABR_HCOONA] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'PRWT_HCOONA') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [PRWT_HCOONA] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'PRTT_HCOONA') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [PRTT_HCOONA] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'ANTIC_HCOONA') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [ANTIC_HCOONA] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'SNOW_DISP_CAP_M3') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [SNOW_DISP_CAP_M3] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'SNOW_MELT_PCT') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [SNOW_MELT_PCT] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'SNOW_DISP_SITE_LP_PCT') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [SNOW_DISP_SITE_LP_PCT] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'SNOW_DISP_SITE_LP_SITES') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [SNOW_DISP_SITE_LP_SITES] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'MELTWATER_POND_PCT') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [MELTWATER_POND_PCT] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'MELTWATER_POND_SITES') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [MELTWATER_POND_SITES] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'MELTWATER_MUN_SEWER_SYS_PCT') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [MELTWATER_MUN_SEWER_SYS_PCT] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'MELTWATER_MUN_SEWER_SYS_SITES') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [MELTWATER_MUN_SEWER_SYS_SITES] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'MELTWATER_WATERCRS_PCT') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [MELTWATER_WATERCRS_PCT] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT', 'MELTWATER_WATERCRS_SITES') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT] ADD [MELTWATER_WATERCRS_SITES] int NULL;
END
GO

IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'SNOW_DISP_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [SNOW_DISP_ID] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'SNOW_DISP_ACH') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [SNOW_DISP_ACH] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'VULN_AREAS_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [VULN_AREAS_ID] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'VULN_AREAS_ACH') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [VULN_AREAS_ACH] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'DEICER_HCOONA') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [DEICER_HCOONA] decimal(18, 0) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'TRTD_ABR_HCOONA') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [TRTD_ABR_HCOONA] decimal(18, 0) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'PRWT_HCOONA') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [PRWT_HCOONA] decimal(18, 0) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'PRTT_HCOONA') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [PRTT_HCOONA] decimal(18, 0) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'ANTIC_HCOONA') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [ANTIC_HCOONA] decimal(18, 0) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'SNOW_DISP_CAP_M3') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [SNOW_DISP_CAP_M3] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'SNOW_MELT_PCT') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [SNOW_MELT_PCT] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'SNOW_DISP_SITE_LP_PCT') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [SNOW_DISP_SITE_LP_PCT] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'SNOW_DISP_SITE_LP_SITES') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [SNOW_DISP_SITE_LP_SITES] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'MELTWATER_POND_PCT') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [MELTWATER_POND_PCT] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'MELTWATER_POND_SITES') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [MELTWATER_POND_SITES] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'MELTWATER_MUN_SEWER_SYS_PCT') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [MELTWATER_MUN_SEWER_SYS_PCT] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'MELTWATER_MUN_SEWER_SYS_SITES') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [MELTWATER_MUN_SEWER_SYS_SITES] int NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'MELTWATER_WATERCRS_PCT') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [MELTWATER_WATERCRS_PCT] decimal(10, 2) NULL;
END
GO
IF COL_LENGTH('dbo.HMR_SALT_REPORT_HIST', 'MELTWATER_WATERCRS_SITES') IS NULL
BEGIN
    ALTER TABLE [dbo].[HMR_SALT_REPORT_HIST] ADD [MELTWATER_WATERCRS_SITES] int NULL;
END
GO

/****** Object:  Trigger [dbo].[HMR_SLTRPT_PK_A_S_IUD_TR]    Script Date: 2024-04-16 11:48:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER TRIGGER [dbo].[HMR_SLTRPT_PK_A_S_IUD_TR] ON [dbo].[HMR_SALT_REPORT] FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON
BEGIN TRY
DECLARE @curr_date datetime;
SET @curr_date = getutcdate();
  IF NOT EXISTS(SELECT * FROM inserted) AND NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- historical
  IF EXISTS(SELECT * FROM deleted)
    update HMR_SALT_REPORT_HIST set END_DATE_HIST = @curr_date where SALT_REPORT_ID in (select SALT_REPORT_ID from deleted) and END_DATE_HIST is null;
  
  IF EXISTS(SELECT * FROM inserted)
    insert into HMR_SALT_REPORT_HIST ([SALT_REPORT_ID], [SERVICE_AREA], [CNTCT_NAME], [EMAIL], [TEL], [PLAN_DEV], [PLAN_REV], [PLAN_UPD], [MGR_TRAIN], [SUPV_TRAIN], [OPR_TRAIN], [MECH_TRAIN], [PATR_TRAIN], [MAT_STOR_ID], [MAT_STOR_ACH], [SALT_APP_ID], [SALT_APP_ACH], [SNOW_DISP_ID], [SNOW_DISP_ACH], [VULN_AREAS_ID], [VULN_AREAS_ACH], [RD_TOT_LEN], [SALT_TOT_DAYS], [DEICER_NACL], [DEICER_MGCL2], [DEICER_CACL2], [DEICER_ACET], [DEICER_HCOONA], [TRTD_ABR_SDST], [TRTD_ABR_NACL], [TRTD_ABR_MGCL2], [TRTD_ABR_CACL2], [TRTD_ABR_HCOONA], [PRWT_NACL], [PRWT_MGCL2], [PRWT_CACL2], [PRWT_ACET], [PRWT_NONCL], [PRWT_HCOONA], [PRTT_NACL], [PRTT_MGCL2], [PRTT_CACL2], [PRTT_ACET], [PRTT_NONCL], [PRTT_HCOONA], [ANTIC_NACL], [ANTIC_MGCL2], [ANTIC_CACL2], [ANTIC_ACET], [ANTIC_NONCL], [ANTIC_HCOONA], [MULTICHL_A_CACL2_PCT], [MULTICHL_A_LTRS], [MULTICHL_A_NACL_PCT], [MULTICHL_A_MGCL2_PCT], [MULTICHL_B_LTRS], [MULTICHL_B_MGCL2_PCT], [MULTICHL_B_NACL_PCT], [MULTICHL_B_CACL2_PCT], [SALT_STRG_SITES_TOT], [ALL_MAT_HNDL_PLAN], [ALL_MAT_HNDL_SITES], [CTRL_DIV_EXT_WAT_PLAN], [CTRL_DIV_EXT_WAT_SITES], [DRAIN_COLL_SYS_PLAN], [DRAIN_COLL_SYS_SITES], [EQP_PRVNT_OVRLOAD_PLAN], [EQP_PRVNT_OVRLOAD_SITES], [MUN_SEWER_SYS_PLAN], [MUN_SEWER_SYS_SITES], [ONGOING_CLNUP_PLAN], [ONGOING_CLNUP_SITES], [OTH_DISCH_PT_PLAN], [OTH_DISCH_PT_SITES], [REMOV_CONT_PLAN], [REMOV_CONT_SITES], [RISK_MGMT_PLAN_PLAN], [RISK_MGMT_PLAN_SITES], [WASTE_WATER_SYS_PLAN], [WASTE_WATER_SYS_SITES], [WATERCRS_PLAN], [WATERCRS_SITES], [NUM_VEHICLES], [VEH_SALT_APP], [VEH_CONV], [VEH_PREWET_EQ], [VEH_DLA], [REG_CALIB], [REG_CALIB_TOT], [IR_THRM_REL], [IR_THRM_TOT], [MET_SVC_REL], [FIX_RWIS_REL], [FIX_RWIS_TOT], [MOB_RWIS_REL], [MOB_RWIS_TOT], [AVL_REL], [AVL_TOT], [SALT_APP_RATE_REL], [SALT_APP_RATE_TOT], [APP_RATE_CHRT_REL], [APP_RATE_CHRT_TOT], [TEST_MDSS_REL], [TEST_SMDS_TOT], [SNOW_DISP_SITE_USED], [SNOW_DISP_SITE_TOT], [SNOW_DISP_CAP_M3], [SNOW_MELT_USED], [SNOW_MELT_PCT], [MELTWATER_DISP_METH_USED], [SNOW_DISP_SITE_LP_PCT], [SNOW_DISP_SITE_LP_SITES], [MELTWATER_POND_PCT], [MELTWATER_POND_SITES], [MELTWATER_MUN_SEWER_SYS_PCT], [MELTWATER_MUN_SEWER_SYS_SITES], [MELTWATER_WATERCRS_PCT], [MELTWATER_WATERCRS_SITES], [COMP_INV], [SET_VULN_AREAS], [ACT_PLAN_PREP], [PROT_MEAS_IMPL], [ENV_MON_COND], [AQUA_LIFE_AREA_ID], [AQUA_LIFE_CHLOR_ID], [AQUA_LIFE_PROT_ID], [DELIM_AREA_ID], [DELIM_AREA_CHLOR_ID], [DELIM_AREA_PROT_ID], [DRINK_WATER_AREA_ID], [DRINK_WATER_CHLOR_ID], [DRINK_WATER_PROT_ID], [VAL_LANDS_AREA_ID], [VAL_LANDS_CHLOR_ID], [VAL_LANDS_PROT_ID], [WETLANDS_AREA_ID], [WETLANDS_CHLOR_ID], [WETLANDS_PROT_ID], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_USERID], [APP_CREATE_TIMESTAMP], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_AUDIT_CREATE_USERID], [DB_AUDIT_CREATE_TIMESTAMP], [DB_AUDIT_LAST_UPDATE_USERID], [DB_AUDIT_LAST_UPDATE_TIMESTAMP], SALT_REPORT_HIST_ID, END_DATE_HIST, EFFECTIVE_DATE_HIST)
      select [SALT_REPORT_ID], [SERVICE_AREA], [CNTCT_NAME], [EMAIL], [TEL], [PLAN_DEV], [PLAN_REV], [PLAN_UPD], [MGR_TRAIN], [SUPV_TRAIN], [OPR_TRAIN], [MECH_TRAIN], [PATR_TRAIN], [MAT_STOR_ID], [MAT_STOR_ACH], [SALT_APP_ID], [SALT_APP_ACH], [SNOW_DISP_ID], [SNOW_DISP_ACH], [VULN_AREAS_ID], [VULN_AREAS_ACH], [RD_TOT_LEN], [SALT_TOT_DAYS], [DEICER_NACL], [DEICER_MGCL2], [DEICER_CACL2], [DEICER_ACET], [DEICER_HCOONA], [TRTD_ABR_SDST], [TRTD_ABR_NACL], [TRTD_ABR_MGCL2], [TRTD_ABR_CACL2], [TRTD_ABR_HCOONA], [PRWT_NACL], [PRWT_MGCL2], [PRWT_CACL2], [PRWT_ACET], [PRWT_NONCL], [PRWT_HCOONA], [PRTT_NACL], [PRTT_MGCL2], [PRTT_CACL2], [PRTT_ACET], [PRTT_NONCL], [PRTT_HCOONA], [ANTIC_NACL], [ANTIC_MGCL2], [ANTIC_CACL2], [ANTIC_ACET], [ANTIC_NONCL], [ANTIC_HCOONA], [MULTICHL_A_CACL2_PCT], [MULTICHL_A_LTRS], [MULTICHL_A_NACL_PCT], [MULTICHL_A_MGCL2_PCT], [MULTICHL_B_LTRS], [MULTICHL_B_MGCL2_PCT], [MULTICHL_B_NACL_PCT], [MULTICHL_B_CACL2_PCT], [SALT_STRG_SITES_TOT], [ALL_MAT_HNDL_PLAN], [ALL_MAT_HNDL_SITES], [CTRL_DIV_EXT_WAT_PLAN], [CTRL_DIV_EXT_WAT_SITES], [DRAIN_COLL_SYS_PLAN], [DRAIN_COLL_SYS_SITES], [EQP_PRVNT_OVRLOAD_PLAN], [EQP_PRVNT_OVRLOAD_SITES], [MUN_SEWER_SYS_PLAN], [MUN_SEWER_SYS_SITES], [ONGOING_CLNUP_PLAN], [ONGOING_CLNUP_SITES], [OTH_DISCH_PT_PLAN], [OTH_DISCH_PT_SITES], [REMOV_CONT_PLAN], [REMOV_CONT_SITES], [RISK_MGMT_PLAN_PLAN], [RISK_MGMT_PLAN_SITES], [WASTE_WATER_SYS_PLAN], [WASTE_WATER_SYS_SITES], [WATERCRS_PLAN], [WATERCRS_SITES], [NUM_VEHICLES], [VEH_SALT_APP], [VEH_CONV], [VEH_PREWET_EQ], [VEH_DLA], [REG_CALIB], [REG_CALIB_TOT], [IR_THRM_REL], [IR_THRM_TOT], [MET_SVC_REL], [FIX_RWIS_REL], [FIX_RWIS_TOT], [MOB_RWIS_REL], [MOB_RWIS_TOT], [AVL_REL], [AVL_TOT], [SALT_APP_RATE_REL], [SALT_APP_RATE_TOT], [APP_RATE_CHRT_REL], [APP_RATE_CHRT_TOT], [TEST_MDSS_REL], [TEST_SMDS_TOT], [SNOW_DISP_SITE_USED], [SNOW_DISP_SITE_TOT], [SNOW_DISP_CAP_M3], [SNOW_MELT_USED], [SNOW_MELT_PCT], [MELTWATER_DISP_METH_USED], [SNOW_DISP_SITE_LP_PCT], [SNOW_DISP_SITE_LP_SITES], [MELTWATER_POND_PCT], [MELTWATER_POND_SITES], [MELTWATER_MUN_SEWER_SYS_PCT], [MELTWATER_MUN_SEWER_SYS_SITES], [MELTWATER_WATERCRS_PCT], [MELTWATER_WATERCRS_SITES], [COMP_INV], [SET_VULN_AREAS], [ACT_PLAN_PREP], [PROT_MEAS_IMPL], [ENV_MON_COND], [AQUA_LIFE_AREA_ID], [AQUA_LIFE_CHLOR_ID], [AQUA_LIFE_PROT_ID], [DELIM_AREA_ID], [DELIM_AREA_CHLOR_ID], [DELIM_AREA_PROT_ID], [DRINK_WATER_AREA_ID], [DRINK_WATER_CHLOR_ID], [DRINK_WATER_PROT_ID], [VAL_LANDS_AREA_ID], [VAL_LANDS_CHLOR_ID], [VAL_LANDS_PROT_ID], [WETLANDS_AREA_ID], [WETLANDS_CHLOR_ID], [WETLANDS_PROT_ID], [CONCURRENCY_CONTROL_NUMBER], [APP_CREATE_USERID], [APP_CREATE_TIMESTAMP], [APP_CREATE_USER_GUID], [APP_CREATE_USER_DIRECTORY], [APP_LAST_UPDATE_USERID], [APP_LAST_UPDATE_TIMESTAMP], [APP_LAST_UPDATE_USER_GUID], [APP_LAST_UPDATE_USER_DIRECTORY], [DB_AUDIT_CREATE_USERID], [DB_AUDIT_CREATE_TIMESTAMP], [DB_AUDIT_LAST_UPDATE_USERID], [DB_AUDIT_LAST_UPDATE_TIMESTAMP], (next value for [dbo].[HMR_SALT_REPORT_H_ID_SEQ]) as [SALT_REPORT_HIST_ID], null as [END_DATE_HIST], @curr_date as [EFFECTIVE_DATE_HIST] from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC hmr_error_handling
END CATCH;
GO
ALTER TABLE [dbo].[HMR_SALT_REPORT] ENABLE TRIGGER [HMR_SLTRPT_PK_A_S_IUD_TR]
GO
/****** Object:  Trigger [dbo].[HMR_SLTRPT_PK_I_S_I_TR]    Script Date: 2024-04-16 11:48:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER TRIGGER [dbo].[HMR_SLTRPT_PK_I_S_I_TR] ON [dbo].[HMR_SALT_REPORT] INSTEAD OF INSERT AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM inserted) 
    RETURN;

  
  insert into HMR_SALT_REPORT ("SALT_REPORT_ID",
      "SERVICE_AREA",
      "CNTCT_NAME",
      "EMAIL",
      "TEL",
      "PLAN_DEV",
      "PLAN_REV",
      "PLAN_UPD",
      "MGR_TRAIN",
      "SUPV_TRAIN",
      "OPR_TRAIN",
      "MECH_TRAIN",
      "PATR_TRAIN",
      "MAT_STOR_ID",
      "MAT_STOR_ACH",
      "SALT_APP_ID",
      "SALT_APP_ACH",
      "SNOW_DISP_ID",
      "SNOW_DISP_ACH",
      "VULN_AREAS_ID",
      "VULN_AREAS_ACH",
      "RD_TOT_LEN",
      "SALT_TOT_DAYS",
      "DEICER_NACL",
      "DEICER_MGCL2",
      "DEICER_CACL2",
      "DEICER_ACET",
      "DEICER_HCOONA",
      "TRTD_ABR_SDST",
      "TRTD_ABR_NACL",
      "TRTD_ABR_MGCL2",
      "TRTD_ABR_CACL2",
      "TRTD_ABR_HCOONA",
      "PRWT_NACL",
      "PRWT_MGCL2",
      "PRWT_CACL2",
      "PRWT_ACET",
      "PRWT_NONCL",
      "PRWT_HCOONA",
      "PRTT_NACL",
      "PRTT_MGCL2",
      "PRTT_CACL2",
      "PRTT_ACET",
      "PRTT_NONCL",
      "PRTT_HCOONA",
      "ANTIC_NACL",
      "ANTIC_MGCL2",
      "ANTIC_CACL2",
      "ANTIC_ACET",
      "ANTIC_NONCL",
      "ANTIC_HCOONA",
      "MULTICHL_A_CACL2_PCT",
      "MULTICHL_A_LTRS",
      "MULTICHL_A_NACL_PCT",
      "MULTICHL_A_MGCL2_PCT",
      "MULTICHL_B_LTRS",
      "MULTICHL_B_MGCL2_PCT",
      "MULTICHL_B_NACL_PCT",
      "MULTICHL_B_CACL2_PCT",
      "SALT_STRG_SITES_TOT",
      "ALL_MAT_HNDL_PLAN",
      "ALL_MAT_HNDL_SITES",
      "CTRL_DIV_EXT_WAT_PLAN",
      "CTRL_DIV_EXT_WAT_SITES",
      "DRAIN_COLL_SYS_PLAN",
      "DRAIN_COLL_SYS_SITES",
      "EQP_PRVNT_OVRLOAD_PLAN",
      "EQP_PRVNT_OVRLOAD_SITES",
      "MUN_SEWER_SYS_PLAN",
      "MUN_SEWER_SYS_SITES",
      "ONGOING_CLNUP_PLAN",
      "ONGOING_CLNUP_SITES",
      "OTH_DISCH_PT_PLAN",
      "OTH_DISCH_PT_SITES",
      "REMOV_CONT_PLAN",
      "REMOV_CONT_SITES",
      "RISK_MGMT_PLAN_PLAN",
      "RISK_MGMT_PLAN_SITES",
      "WASTE_WATER_SYS_PLAN",
      "WASTE_WATER_SYS_SITES",
      "WATERCRS_PLAN",
      "WATERCRS_SITES",
      "NUM_VEHICLES",
      "VEH_SALT_APP",
      "VEH_CONV",
      "VEH_PREWET_EQ",
      "VEH_DLA",
      "REG_CALIB",
      "REG_CALIB_TOT",
      "IR_THRM_REL",
      "IR_THRM_TOT",
      "MET_SVC_REL",
      "FIX_RWIS_REL",
      "FIX_RWIS_TOT",
      "MOB_RWIS_REL",
      "MOB_RWIS_TOT",
      "AVL_REL",
      "AVL_TOT",
      "SALT_APP_RATE_REL",
      "SALT_APP_RATE_TOT",
      "APP_RATE_CHRT_REL",
      "APP_RATE_CHRT_TOT",
      "TEST_MDSS_REL",
      "TEST_SMDS_TOT",
      "SNOW_DISP_SITE_USED",
      "SNOW_DISP_SITE_TOT",
      "SNOW_DISP_CAP_M3",
      "SNOW_MELT_USED",
      "SNOW_MELT_PCT",
      "MELTWATER_DISP_METH_USED",
      "SNOW_DISP_SITE_LP_PCT",
      "SNOW_DISP_SITE_LP_SITES",
      "MELTWATER_POND_PCT",
      "MELTWATER_POND_SITES",
      "MELTWATER_MUN_SEWER_SYS_PCT",
      "MELTWATER_MUN_SEWER_SYS_SITES",
      "MELTWATER_WATERCRS_PCT",
      "MELTWATER_WATERCRS_SITES",
      "COMP_INV",
      "SET_VULN_AREAS",
      "ACT_PLAN_PREP",
      "PROT_MEAS_IMPL",
      "ENV_MON_COND",
      "AQUA_LIFE_AREA_ID",
      "AQUA_LIFE_CHLOR_ID",
      "AQUA_LIFE_PROT_ID",
      "DELIM_AREA_ID",
      "DELIM_AREA_CHLOR_ID",
      "DELIM_AREA_PROT_ID",
      "DRINK_WATER_AREA_ID",
      "DRINK_WATER_CHLOR_ID",
      "DRINK_WATER_PROT_ID",
      "VAL_LANDS_AREA_ID",
      "VAL_LANDS_CHLOR_ID",
      "VAL_LANDS_PROT_ID",
      "WETLANDS_AREA_ID",
      "WETLANDS_CHLOR_ID",
      "WETLANDS_PROT_ID",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_USERID",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USER_GUID",
      "APP_CREATE_USER_DIRECTORY",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY")
    select "SALT_REPORT_ID",
      "SERVICE_AREA",
      "CNTCT_NAME",
      "EMAIL",
      "TEL",
      "PLAN_DEV",
      "PLAN_REV",
      "PLAN_UPD",
      "MGR_TRAIN",
      "SUPV_TRAIN",
      "OPR_TRAIN",
      "MECH_TRAIN",
      "PATR_TRAIN",
      "MAT_STOR_ID",
      "MAT_STOR_ACH",
      "SALT_APP_ID",
      "SALT_APP_ACH",
      "SNOW_DISP_ID",
      "SNOW_DISP_ACH",
      "VULN_AREAS_ID",
      "VULN_AREAS_ACH",
      "RD_TOT_LEN",
      "SALT_TOT_DAYS",
      "DEICER_NACL",
      "DEICER_MGCL2",
      "DEICER_CACL2",
      "DEICER_ACET",
      "DEICER_HCOONA",
      "TRTD_ABR_SDST",
      "TRTD_ABR_NACL",
      "TRTD_ABR_MGCL2",
      "TRTD_ABR_CACL2",
      "TRTD_ABR_HCOONA",
      "PRWT_NACL",
      "PRWT_MGCL2",
      "PRWT_CACL2",
      "PRWT_ACET",
      "PRWT_NONCL",
      "PRWT_HCOONA",
      "PRTT_NACL",
      "PRTT_MGCL2",
      "PRTT_CACL2",
      "PRTT_ACET",
      "PRTT_NONCL",
      "PRTT_HCOONA",
      "ANTIC_NACL",
      "ANTIC_MGCL2",
      "ANTIC_CACL2",
      "ANTIC_ACET",
      "ANTIC_NONCL",
      "ANTIC_HCOONA",
      "MULTICHL_A_CACL2_PCT",
      "MULTICHL_A_LTRS",
      "MULTICHL_A_NACL_PCT",
      "MULTICHL_A_MGCL2_PCT",
      "MULTICHL_B_LTRS",
      "MULTICHL_B_MGCL2_PCT",
      "MULTICHL_B_NACL_PCT",
      "MULTICHL_B_CACL2_PCT",
      "SALT_STRG_SITES_TOT",
      "ALL_MAT_HNDL_PLAN",
      "ALL_MAT_HNDL_SITES",
      "CTRL_DIV_EXT_WAT_PLAN",
      "CTRL_DIV_EXT_WAT_SITES",
      "DRAIN_COLL_SYS_PLAN",
      "DRAIN_COLL_SYS_SITES",
      "EQP_PRVNT_OVRLOAD_PLAN",
      "EQP_PRVNT_OVRLOAD_SITES",
      "MUN_SEWER_SYS_PLAN",
      "MUN_SEWER_SYS_SITES",
      "ONGOING_CLNUP_PLAN",
      "ONGOING_CLNUP_SITES",
      "OTH_DISCH_PT_PLAN",
      "OTH_DISCH_PT_SITES",
      "REMOV_CONT_PLAN",
      "REMOV_CONT_SITES",
      "RISK_MGMT_PLAN_PLAN",
      "RISK_MGMT_PLAN_SITES",
      "WASTE_WATER_SYS_PLAN",
      "WASTE_WATER_SYS_SITES",
      "WATERCRS_PLAN",
      "WATERCRS_SITES",
      "NUM_VEHICLES",
      "VEH_SALT_APP",
      "VEH_CONV",
      "VEH_PREWET_EQ",
      "VEH_DLA",
      "REG_CALIB",
      "REG_CALIB_TOT",
      "IR_THRM_REL",
      "IR_THRM_TOT",
      "MET_SVC_REL",
      "FIX_RWIS_REL",
      "FIX_RWIS_TOT",
      "MOB_RWIS_REL",
      "MOB_RWIS_TOT",
      "AVL_REL",
      "AVL_TOT",
      "SALT_APP_RATE_REL",
      "SALT_APP_RATE_TOT",
      "APP_RATE_CHRT_REL",
      "APP_RATE_CHRT_TOT",
      "TEST_MDSS_REL",
      "TEST_SMDS_TOT",
      "SNOW_DISP_SITE_USED",
      "SNOW_DISP_SITE_TOT",
      "SNOW_DISP_CAP_M3",
      "SNOW_MELT_USED",
      "SNOW_MELT_PCT",
      "MELTWATER_DISP_METH_USED",
      "SNOW_DISP_SITE_LP_PCT",
      "SNOW_DISP_SITE_LP_SITES",
      "MELTWATER_POND_PCT",
      "MELTWATER_POND_SITES",
      "MELTWATER_MUN_SEWER_SYS_PCT",
      "MELTWATER_MUN_SEWER_SYS_SITES",
      "MELTWATER_WATERCRS_PCT",
      "MELTWATER_WATERCRS_SITES",
      "COMP_INV",
      "SET_VULN_AREAS",
      "ACT_PLAN_PREP",
      "PROT_MEAS_IMPL",
      "ENV_MON_COND",
      "AQUA_LIFE_AREA_ID",
      "AQUA_LIFE_CHLOR_ID",
      "AQUA_LIFE_PROT_ID",
      "DELIM_AREA_ID",
      "DELIM_AREA_CHLOR_ID",
      "DELIM_AREA_PROT_ID",
      "DRINK_WATER_AREA_ID",
      "DRINK_WATER_CHLOR_ID",
      "DRINK_WATER_PROT_ID",
      "VAL_LANDS_AREA_ID",
      "VAL_LANDS_CHLOR_ID",
      "VAL_LANDS_PROT_ID",
      "WETLANDS_AREA_ID",
      "WETLANDS_CHLOR_ID",
      "WETLANDS_PROT_ID",
      "CONCURRENCY_CONTROL_NUMBER",
      "APP_CREATE_USERID",
      "APP_CREATE_TIMESTAMP",
      "APP_CREATE_USER_GUID",
      "APP_CREATE_USER_DIRECTORY",
      "APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY"
    from inserted;

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC hmr_error_handling
END CATCH;
GO
ALTER TABLE [dbo].[HMR_SALT_REPORT] ENABLE TRIGGER [HMR_SLTRPT_PK_I_S_I_TR]
GO
/****** Object:  Trigger [dbo].[HMR_SLTRPT_PK_I_S_U_TR]    Script Date: 2024-04-16 11:48:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER TRIGGER [dbo].[HMR_SLTRPT_PK_I_S_U_TR] ON [dbo].[HMR_SALT_REPORT] INSTEAD OF UPDATE AS
SET NOCOUNT ON
BEGIN TRY
  IF NOT EXISTS(SELECT * FROM deleted) 
    RETURN;

  -- validate concurrency control
  if exists (select 1 from inserted, deleted where inserted.CONCURRENCY_CONTROL_NUMBER != deleted.CONCURRENCY_CONTROL_NUMBER+1 AND inserted.SALT_REPORT_ID = deleted.SALT_REPORT_ID)
    raiserror('CONCURRENCY FAILURE.',16,1)


  -- update statement
  update HMR_SALT_REPORT
    set "SALT_REPORT_ID" = inserted."SALT_REPORT_ID",
      "SERVICE_AREA" = inserted."SERVICE_AREA",
      "CNTCT_NAME" = inserted."CNTCT_NAME",
      "EMAIL" = inserted."EMAIL",
      "TEL" = inserted."TEL",
      "PLAN_DEV" = inserted."PLAN_DEV",
      "PLAN_REV" = inserted."PLAN_REV",
      "PLAN_UPD" = inserted."PLAN_UPD",
      "MGR_TRAIN" = inserted."MGR_TRAIN",
      "SUPV_TRAIN" = inserted."SUPV_TRAIN",
      "OPR_TRAIN" = inserted."OPR_TRAIN",
      "MECH_TRAIN" = inserted."MECH_TRAIN",
      "PATR_TRAIN" = inserted."PATR_TRAIN",
      "MAT_STOR_ID" = inserted."MAT_STOR_ID",
      "MAT_STOR_ACH" = inserted."MAT_STOR_ACH",
      "SALT_APP_ID" = inserted."SALT_APP_ID",
      "SALT_APP_ACH" = inserted."SALT_APP_ACH",
      "SNOW_DISP_ID" = inserted."SNOW_DISP_ID",
      "SNOW_DISP_ACH" = inserted."SNOW_DISP_ACH",
      "VULN_AREAS_ID" = inserted."VULN_AREAS_ID",
      "VULN_AREAS_ACH" = inserted."VULN_AREAS_ACH",
      "RD_TOT_LEN" = inserted."RD_TOT_LEN",
      "SALT_TOT_DAYS" = inserted."SALT_TOT_DAYS",
      "DEICER_NACL" = inserted."DEICER_NACL",
      "DEICER_MGCL2" = inserted."DEICER_MGCL2",
      "DEICER_CACL2" = inserted."DEICER_CACL2",
      "DEICER_ACET" = inserted."DEICER_ACET",
      "DEICER_HCOONA" = inserted."DEICER_HCOONA",
      "TRTD_ABR_SDST" = inserted."TRTD_ABR_SDST",
      "TRTD_ABR_NACL" = inserted."TRTD_ABR_NACL",
      "TRTD_ABR_MGCL2" = inserted."TRTD_ABR_MGCL2",
      "TRTD_ABR_CACL2" = inserted."TRTD_ABR_CACL2",
      "TRTD_ABR_HCOONA" = inserted."TRTD_ABR_HCOONA",
      "PRWT_NACL" = inserted."PRWT_NACL",
      "PRWT_MGCL2" = inserted."PRWT_MGCL2",
      "PRWT_CACL2" = inserted."PRWT_CACL2",
      "PRWT_ACET" = inserted."PRWT_ACET",
      "PRWT_NONCL" = inserted."PRWT_NONCL",
      "PRWT_HCOONA" = inserted."PRWT_HCOONA",
      "PRTT_NACL" = inserted."PRTT_NACL",
      "PRTT_MGCL2" = inserted."PRTT_MGCL2",
      "PRTT_CACL2" = inserted."PRTT_CACL2",
      "PRTT_ACET" = inserted."PRTT_ACET",
      "PRTT_NONCL" = inserted."PRTT_NONCL",
      "PRTT_HCOONA" = inserted."PRTT_HCOONA",
      "ANTIC_NACL" = inserted."ANTIC_NACL",
      "ANTIC_MGCL2" = inserted."ANTIC_MGCL2",
      "ANTIC_CACL2" = inserted."ANTIC_CACL2",
      "ANTIC_ACET" = inserted."ANTIC_ACET",
      "ANTIC_NONCL" = inserted."ANTIC_NONCL",
      "ANTIC_HCOONA" = inserted."ANTIC_HCOONA",
      "MULTICHL_A_CACL2_PCT" = inserted."MULTICHL_A_CACL2_PCT",
      "MULTICHL_A_LTRS" = inserted."MULTICHL_A_LTRS",
      "MULTICHL_A_NACL_PCT" = inserted."MULTICHL_A_NACL_PCT",
      "MULTICHL_A_MGCL2_PCT" = inserted."MULTICHL_A_MGCL2_PCT",
      "MULTICHL_B_LTRS" = inserted."MULTICHL_B_LTRS",
      "MULTICHL_B_MGCL2_PCT" = inserted."MULTICHL_B_MGCL2_PCT",
      "MULTICHL_B_NACL_PCT" = inserted."MULTICHL_B_NACL_PCT",
      "MULTICHL_B_CACL2_PCT" = inserted."MULTICHL_B_CACL2_PCT",
      "SALT_STRG_SITES_TOT" = inserted."SALT_STRG_SITES_TOT",
      "ALL_MAT_HNDL_PLAN" = inserted."ALL_MAT_HNDL_PLAN",
      "ALL_MAT_HNDL_SITES" = inserted."ALL_MAT_HNDL_SITES",
      "CTRL_DIV_EXT_WAT_PLAN" = inserted."CTRL_DIV_EXT_WAT_PLAN",
      "CTRL_DIV_EXT_WAT_SITES" = inserted."CTRL_DIV_EXT_WAT_SITES",
      "DRAIN_COLL_SYS_PLAN" = inserted."DRAIN_COLL_SYS_PLAN",
      "DRAIN_COLL_SYS_SITES" = inserted."DRAIN_COLL_SYS_SITES",
      "EQP_PRVNT_OVRLOAD_PLAN" = inserted."EQP_PRVNT_OVRLOAD_PLAN",
      "EQP_PRVNT_OVRLOAD_SITES" = inserted."EQP_PRVNT_OVRLOAD_SITES",
      "MUN_SEWER_SYS_PLAN" = inserted."MUN_SEWER_SYS_PLAN",
      "MUN_SEWER_SYS_SITES" = inserted."MUN_SEWER_SYS_SITES",
      "ONGOING_CLNUP_PLAN" = inserted."ONGOING_CLNUP_PLAN",
      "ONGOING_CLNUP_SITES" = inserted."ONGOING_CLNUP_SITES",
      "OTH_DISCH_PT_PLAN" = inserted."OTH_DISCH_PT_PLAN",
      "OTH_DISCH_PT_SITES" = inserted."OTH_DISCH_PT_SITES",
      "REMOV_CONT_PLAN" = inserted."REMOV_CONT_PLAN",
      "REMOV_CONT_SITES" = inserted."REMOV_CONT_SITES",
      "RISK_MGMT_PLAN_PLAN" = inserted."RISK_MGMT_PLAN_PLAN",
      "RISK_MGMT_PLAN_SITES" = inserted."RISK_MGMT_PLAN_SITES",
      "WASTE_WATER_SYS_PLAN" = inserted."WASTE_WATER_SYS_PLAN",
      "WASTE_WATER_SYS_SITES" = inserted."WASTE_WATER_SYS_SITES",
      "WATERCRS_PLAN" = inserted."WATERCRS_PLAN",
      "WATERCRS_SITES" = inserted."WATERCRS_SITES",
      "NUM_VEHICLES" = inserted."NUM_VEHICLES",
      "VEH_SALT_APP" = inserted."VEH_SALT_APP",
      "VEH_CONV" = inserted."VEH_CONV",
      "VEH_PREWET_EQ" = inserted."VEH_PREWET_EQ",
      "VEH_DLA" = inserted."VEH_DLA",
      "REG_CALIB" = inserted."REG_CALIB",
      "REG_CALIB_TOT" = inserted."REG_CALIB_TOT",
      "IR_THRM_REL" = inserted."IR_THRM_REL",
      "IR_THRM_TOT" = inserted."IR_THRM_TOT",
      "MET_SVC_REL" = inserted."MET_SVC_REL",
      "FIX_RWIS_REL" = inserted."FIX_RWIS_REL",
      "FIX_RWIS_TOT" = inserted."FIX_RWIS_TOT",
      "MOB_RWIS_REL" = inserted."MOB_RWIS_REL",
      "MOB_RWIS_TOT" = inserted."MOB_RWIS_TOT",
      "AVL_REL" = inserted."AVL_REL",
      "AVL_TOT" = inserted."AVL_TOT",
      "SALT_APP_RATE_REL" = inserted."SALT_APP_RATE_REL",
      "SALT_APP_RATE_TOT" = inserted."SALT_APP_RATE_TOT",
      "APP_RATE_CHRT_REL" = inserted."APP_RATE_CHRT_REL",
      "APP_RATE_CHRT_TOT" = inserted."APP_RATE_CHRT_TOT",
      "TEST_MDSS_REL" = inserted."TEST_MDSS_REL",
      "TEST_SMDS_TOT" = inserted."TEST_SMDS_TOT",
      "SNOW_DISP_SITE_USED" = inserted."SNOW_DISP_SITE_USED",
      "SNOW_DISP_SITE_TOT" = inserted."SNOW_DISP_SITE_TOT",
      "SNOW_DISP_CAP_M3" = inserted."SNOW_DISP_CAP_M3",
      "SNOW_MELT_USED" = inserted."SNOW_MELT_USED",
      "SNOW_MELT_PCT" = inserted."SNOW_MELT_PCT",
      "MELTWATER_DISP_METH_USED" = inserted."MELTWATER_DISP_METH_USED",
      "SNOW_DISP_SITE_LP_PCT" = inserted."SNOW_DISP_SITE_LP_PCT",
      "SNOW_DISP_SITE_LP_SITES" = inserted."SNOW_DISP_SITE_LP_SITES",
      "MELTWATER_POND_PCT" = inserted."MELTWATER_POND_PCT",
      "MELTWATER_POND_SITES" = inserted."MELTWATER_POND_SITES",
      "MELTWATER_MUN_SEWER_SYS_PCT" = inserted."MELTWATER_MUN_SEWER_SYS_PCT",
      "MELTWATER_MUN_SEWER_SYS_SITES" = inserted."MELTWATER_MUN_SEWER_SYS_SITES",
      "MELTWATER_WATERCRS_PCT" = inserted."MELTWATER_WATERCRS_PCT",
      "MELTWATER_WATERCRS_SITES" = inserted."MELTWATER_WATERCRS_SITES",
      "COMP_INV" = inserted."COMP_INV",
      "SET_VULN_AREAS" = inserted."SET_VULN_AREAS",
      "ACT_PLAN_PREP" = inserted."ACT_PLAN_PREP",
      "PROT_MEAS_IMPL" = inserted."PROT_MEAS_IMPL",
      "ENV_MON_COND" = inserted."ENV_MON_COND",
      "AQUA_LIFE_AREA_ID" = inserted."AQUA_LIFE_AREA_ID",
      "AQUA_LIFE_CHLOR_ID" = inserted."AQUA_LIFE_CHLOR_ID",
      "AQUA_LIFE_PROT_ID" = inserted."AQUA_LIFE_PROT_ID",
      "DELIM_AREA_ID" = inserted."DELIM_AREA_ID",
      "DELIM_AREA_CHLOR_ID" = inserted."DELIM_AREA_CHLOR_ID",
      "DELIM_AREA_PROT_ID" = inserted."DELIM_AREA_PROT_ID",
      "DRINK_WATER_AREA_ID" = inserted."DRINK_WATER_AREA_ID",
      "DRINK_WATER_CHLOR_ID" = inserted."DRINK_WATER_CHLOR_ID",
      "DRINK_WATER_PROT_ID" = inserted."DRINK_WATER_PROT_ID",
      "VAL_LANDS_AREA_ID" = inserted."VAL_LANDS_AREA_ID",
      "VAL_LANDS_CHLOR_ID" = inserted."VAL_LANDS_CHLOR_ID",
      "VAL_LANDS_PROT_ID" = inserted."VAL_LANDS_PROT_ID",
      "WETLANDS_AREA_ID" = inserted."WETLANDS_AREA_ID",
      "WETLANDS_CHLOR_ID" = inserted."WETLANDS_CHLOR_ID",
      "WETLANDS_PROT_ID" = inserted."WETLANDS_PROT_ID",
      "CONCURRENCY_CONTROL_NUMBER" = inserted."CONCURRENCY_CONTROL_NUMBER",
      "APP_LAST_UPDATE_USERID" = inserted."APP_LAST_UPDATE_USERID",
      "APP_LAST_UPDATE_TIMESTAMP" = inserted."APP_LAST_UPDATE_TIMESTAMP",
      "APP_LAST_UPDATE_USER_GUID" = inserted."APP_LAST_UPDATE_USER_GUID",
      "APP_LAST_UPDATE_USER_DIRECTORY" = inserted."APP_LAST_UPDATE_USER_DIRECTORY"
    , DB_AUDIT_LAST_UPDATE_TIMESTAMP = getutcdate()
    , DB_AUDIT_LAST_UPDATE_USERID = user_name()
    from HMR_SALT_REPORT
    inner join inserted
    on (HMR_SALT_REPORT.SALT_REPORT_ID = inserted.SALT_REPORT_ID);

END TRY
BEGIN CATCH
   IF @@trancount > 0 ROLLBACK TRANSACTION
   EXEC hmr_error_handling
END CATCH;
GO
ALTER TABLE [dbo].[HMR_SALT_REPORT] ENABLE TRIGGER [HMR_SLTRPT_PK_I_S_U_TR]
GO
