/* ---------------------------------------------------------------------- */
/* Script generated with: DeZign for Databases 11.1.0                     */
/* Target DBMS:           MS SQL Server 2017                              */
/* Project file:          HMR_INC.dez                                     */
/* Project name:                                                          */
/* Author:                                                                */
/* Script type:           Alter database script                           */
/* Created on:            2020-01-16 03:34                                */
/* ---------------------------------------------------------------------- */

-- =============================================
-- Author:		Ben Driver
-- Create date: 2020-01-16
-- Updates: 
--	2020-01-02 - v0.14 Changes for Sprint 4:  Corrected Rockfall field name [MCRR_INCIDENT_NUMBER], Added ROW_NUM to all record level tables, Added boolean for flagging overwritten submission rows.
-- 
-- Description:	base DDL for HMR database.  Generated from modeling tool.
-- =============================================


USE HMR_DEV; -- uncomment appropriate instance
--USE HMR_TST;
--USE HMR_UAT;
--USE HMR_PRD;
GO

/* ---------------------------------------------------------------------- */
/* Drop foreign key constraints                                           */
/* ---------------------------------------------------------------------- */

GO


ALTER TABLE [dbo].[HMR_ROCKFALL_REPORT] DROP CONSTRAINT [HMR_RCKFL_RPT_SUBM_OBJ_FK]
GO


ALTER TABLE [dbo].[HMR_ROCKFALL_REPORT] DROP CONSTRAINT [HMR_RKFLL_RRT_SUBM_STAT_FK]
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_ROW] DROP CONSTRAINT [HMR_SUBM_RW_SUBM_STAT_FK]
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_ROW] DROP CONSTRAINT [HMR_SUBM_RW_HMR_SUBM_OBJ_FK]
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] DROP CONSTRAINT [HMR_WLDLF_RPT_HMR_SRV_ARA_FK]
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] DROP CONSTRAINT [HMR_WLDLF_RPT_SUBM_OBJ_FK]
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] DROP CONSTRAINT [HMR_WLDLF_RRT_SUBM_STAT_FK]
GO


ALTER TABLE [dbo].[HMR_WORK_REPORT] DROP CONSTRAINT [HMR_WRK_RRT_SUBM_STAT_FK]
GO


ALTER TABLE [dbo].[HMR_WORK_REPORT] DROP CONSTRAINT [HMR_WRK_RRT_SUBM_OBJ_FK]
GO


ALTER TABLE [dbo].[HMR_WORK_REPORT] DROP CONSTRAINT [HMR_WRK_RRT_SRV_ARA_FK]
GO


/* ---------------------------------------------------------------------- */
/* Drop and recreate table "dbo.HMR_ROCKFALL_REPORT"                      */
/* ---------------------------------------------------------------------- */

GO


ALTER TABLE [dbo].[HMR_ROCKFALL_REPORT] DROP CONSTRAINT [HMR_RCKFL_RPT_PK]
GO


CREATE TABLE [dbo].[HMR_ROCKFALL_REPORT_TMP] (
    [ROCKFALL_REPORT_ID] NUMERIC(9) DEFAULT NEXT VALUE FOR [HMR_RCKF_ID_SEQ] NOT NULL,
    [SUBMISSION_OBJECT_ID] NUMERIC(9) NOT NULL,
    [ROW_NUM] NUMERIC(9),
    [VALIDATION_STATUS_ID] NUMERIC(9),
    [MCRR_INCIDENT_NUMBER] VARCHAR(12),
    [ESTIMATED_ROCKFALL_DATE] DATE,
    [ESTIMATED_ROCKFALL_TIME] TIME,
    [START_LATITUDE] NUMERIC(11,6),
    [START_LONGITUDE] NUMERIC(11,6),
    [END_LATITUDE] NUMERIC(11,6),
    [END_LONGITUDE] NUMERIC(11,6),
    [HIGHWAY_UNIQUE_NUMBER] VARCHAR(16),
    [HIGHWAY_UNIQUE_NAME] VARCHAR(255),
    [LANDMARK] VARCHAR(8),
    [LAND_MARK_NAME] VARCHAR(255),
    [START_OFFSET] NUMERIC(7,3),
    [END_OFFSET] NUMERIC(7,3),
    [DIRECTION_FROM_LANDMARK] VARCHAR(1),
    [LOCATION_DESCRIPTION] VARCHAR(4000),
    [DITCH_VOLUME] VARCHAR(30),
    [TRAVELLED_LANES_VOLUME] VARCHAR(30),
    [OTHER_VOLUME] NUMERIC(6,2),
    [HEAVY_PRECIP] VARCHAR(1),
    [FREEZE_THAW] VARCHAR(1),
    [DITCH_SNOW_ICE] VARCHAR(1),
    [VEHICLE_DAMAGE] VARCHAR(1),
    [COMMENTS] VARCHAR(4000),
    [REPORTER_NAME] VARCHAR(150),
    [MC_PHONE_NUMBER] VARCHAR(12),
    [REPORT_DATE] DATE,
    [CONCURRENCY_CONTROL_NUMBER] BIGINT DEFAULT 1 NOT NULL,
    [APP_CREATE_USERID] VARCHAR(30) NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [APP_CREATE_USER_DIRECTORY] VARCHAR(12) NOT NULL,
    [APP_LAST_UPDATE_USERID] VARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [APP_LAST_UPDATE_USER_DIRECTORY] VARCHAR(12) NOT NULL,
    [DB_AUDIT_CREATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_CREATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL)
GO


-- Manual adjustment to preserve data in changed field name [MAJOR_INCIDENT_NUMBER] to [MCRR_INCIDENT_NUMBER]
INSERT INTO [dbo].[HMR_ROCKFALL_REPORT_TMP]
    ([ROCKFALL_REPORT_ID],[SUBMISSION_OBJECT_ID],[VALIDATION_STATUS_ID],[MCRR_INCIDENT_NUMBER],[ESTIMATED_ROCKFALL_DATE],[ESTIMATED_ROCKFALL_TIME],[START_LATITUDE],[START_LONGITUDE],[END_LATITUDE],[END_LONGITUDE],[HIGHWAY_UNIQUE_NUMBER],[HIGHWAY_UNIQUE_NAME],[LANDMARK],[LAND_MARK_NAME],[START_OFFSET],[END_OFFSET],[DIRECTION_FROM_LANDMARK],[LOCATION_DESCRIPTION],[DITCH_VOLUME],[TRAVELLED_LANES_VOLUME],[OTHER_VOLUME],[HEAVY_PRECIP],[FREEZE_THAW],[DITCH_SNOW_ICE],[VEHICLE_DAMAGE],[COMMENTS],[REPORTER_NAME],[MC_PHONE_NUMBER],[REPORT_DATE],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_CREATE_USER_DIRECTORY],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[APP_LAST_UPDATE_USER_DIRECTORY],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP])
SELECT
    [ROCKFALL_REPORT_ID],[SUBMISSION_OBJECT_ID],[VALIDATION_STATUS_ID],[MAJOR_INCIDENT_NUMBER],[ESTIMATED_ROCKFALL_DATE],[ESTIMATED_ROCKFALL_TIME],[START_LATITUDE],[START_LONGITUDE],[END_LATITUDE],[END_LONGITUDE],[HIGHWAY_UNIQUE_NUMBER],[HIGHWAY_UNIQUE_NAME],[LANDMARK],[LAND_MARK_NAME],[START_OFFSET],[END_OFFSET],[DIRECTION_FROM_LANDMARK],[LOCATION_DESCRIPTION],[DITCH_VOLUME],[TRAVELLED_LANES_VOLUME],[OTHER_VOLUME],[HEAVY_PRECIP],[FREEZE_THAW],[DITCH_SNOW_ICE],[VEHICLE_DAMAGE],[COMMENTS],[REPORTER_NAME],[MC_PHONE_NUMBER],[REPORT_DATE],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_CREATE_USER_DIRECTORY],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[APP_LAST_UPDATE_USER_DIRECTORY],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP]
FROM [dbo].[HMR_ROCKFALL_REPORT]
GO


DROP INDEX [dbo].[HMR_ROCKFALL_REPORT].[HMR_RCKFL_RPT_FK_I]
GO


DROP TABLE [dbo].[HMR_ROCKFALL_REPORT]
GO


EXEC sp_rename '[dbo].[HMR_ROCKFALL_REPORT_TMP]', 'HMR_ROCKFALL_REPORT', 'OBJECT'
GO


ALTER TABLE [dbo].[HMR_ROCKFALL_REPORT] ADD CONSTRAINT [HMR_RCKFL_RPT_PK] 
    PRIMARY KEY CLUSTERED ([ROCKFALL_REPORT_ID])
GO


CREATE NONCLUSTERED INDEX [HMR_RCKFL_RPT_FK_I] ON [dbo].[HMR_ROCKFALL_REPORT] ([SUBMISSION_OBJECT_ID] ASC)
GO


EXECUTE sp_addextendedproperty N'MS_Description', N'Relative row number the record was located within a submission.', 'SCHEMA', N'dbo', 'TABLE', N'HMR_ROCKFALL_REPORT', 'COLUMN', N'ROW_NUM'
GO


EXECUTE sp_addextendedproperty N'MS_Description', N'Rockfall reporting incident number. Unique work report record number from the Contractor maintenance management system.', 'SCHEMA', N'dbo', 'TABLE', N'HMR_ROCKFALL_REPORT', 'COLUMN', N'MCRR_INCIDENT_NUMBER'
GO


/* ---------------------------------------------------------------------- */
/* Drop and recreate table "dbo.HMR_SUBMISSION_ROW"                       */
/* ---------------------------------------------------------------------- */

GO


ALTER TABLE [dbo].[HMR_SUBMISSION_ROW] DROP CONSTRAINT [HMR_SUBM_RW_PK]
GO


CREATE TABLE [dbo].[HMR_SUBMISSION_ROW_TMP] (
    [ROW_ID] NUMERIC(9) DEFAULT NEXT VALUE FOR [HMR_SUBM_RW_ID_SEQ] NOT NULL,
    [SUBMISSION_OBJECT_ID] NUMERIC(9) NOT NULL,
    [ROW_STATUS_ID] NUMERIC(9),
    [ROW_NUM] NUMERIC(9),
    [RECORD_NUMBER] VARCHAR(8),
    [ROW_VALUE] VARCHAR(4000),
    [ROW_HASH] VARCHAR(256),
    [IS_RESUBMITTED] VARCHAR(40),
    [ERROR_DETAIL] VARCHAR(4000),
    [CONCURRENCY_CONTROL_NUMBER] BIGINT DEFAULT 1 NOT NULL,
    [APP_CREATE_USERID] VARCHAR(30) NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [APP_CREATE_USER_DIRECTORY] VARCHAR(12) NOT NULL,
    [APP_LAST_UPDATE_USERID] VARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [APP_LAST_UPDATE_USER_DIRECTORY] VARCHAR(12) NOT NULL,
    [DB_AUDIT_CREATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_CREATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL)
GO


INSERT INTO [dbo].[HMR_SUBMISSION_ROW_TMP]
    ([ROW_ID],[SUBMISSION_OBJECT_ID],[ROW_STATUS_ID],[RECORD_NUMBER],[ROW_VALUE],[ROW_HASH],[ERROR_DETAIL],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_CREATE_USER_DIRECTORY],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[APP_LAST_UPDATE_USER_DIRECTORY],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP])
SELECT
    [ROW_ID],[SUBMISSION_OBJECT_ID],[ROW_STATUS_ID],[RECORD_NUMBER],[ROW_VALUE],[ROW_HASH],[ERROR_DETAIL],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_CREATE_USER_DIRECTORY],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[APP_LAST_UPDATE_USER_DIRECTORY],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP]
FROM [dbo].[HMR_SUBMISSION_ROW]
GO


DROP TABLE [dbo].[HMR_SUBMISSION_ROW]
GO


EXEC sp_rename '[dbo].[HMR_SUBMISSION_ROW_TMP]', 'HMR_SUBMISSION_ROW', 'OBJECT'
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_ROW] ADD CONSTRAINT [HMR_SUBM_RW_PK] 
    PRIMARY KEY CLUSTERED ([ROW_ID])
GO


EXECUTE sp_addextendedproperty N'MS_Description', N'Relative row number within the SUBMISSION_OBJECT.', 'SCHEMA', N'dbo', 'TABLE', N'HMR_SUBMISSION_ROW', 'COLUMN', N'ROW_NUM'
GO


EXECUTE sp_addextendedproperty N'MS_Description', N'Indicates if the RECORD_NUMBER for the same CONTRACT_TERM and PARTY has been previously processed successfully and is being overwritten by a subsequent submission row.', 'SCHEMA', N'dbo', 'TABLE', N'HMR_SUBMISSION_ROW', 'COLUMN', N'IS_RESUBMITTED'
GO


/* ---------------------------------------------------------------------- */
/* Drop and recreate table "dbo.HMR_WILDLIFE_REPORT"                      */
/* ---------------------------------------------------------------------- */

GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] DROP CONSTRAINT [HMR_WLDLF_RRT_PK]
GO


CREATE TABLE [dbo].[HMR_WILDLIFE_REPORT_TMP] (
    [WILDLIFE_RECORD_ID] NUMERIC(9) DEFAULT NEXT VALUE FOR [HMR_WLDLF_ID_SEQ] NOT NULL,
    [SUBMISSION_OBJECT_ID] NUMERIC(9) NOT NULL,
    [ROW_NUM] NUMERIC(9),
    [VALIDATION_STATUS_ID] NUMERIC(9),
    [RECORD_TYPE] VARCHAR(1),
    [SERVICE_AREA] NUMERIC(9) NOT NULL,
    [ACCIDENT_DATE] DATETIME,
    [TIME_OF_KILL] VARCHAR(1),
    [LATITUDE] NUMERIC(11,6),
    [LONGITUDE] NUMERIC(11,6),
    [HIGHWAY_UNIQUE_NUMBER] VARCHAR(16),
    [LANDMARK] VARCHAR(8),
    [START_OFFSET] NUMERIC(7,3),
    [NEAREST_TOWN] VARCHAR(150),
    [WILDLIFE_SIGN] VARCHAR(1),
    [QUANTITY] NUMERIC(4),
    [SPECIES] NUMERIC(2),
    [SEX] VARCHAR(1),
    [AGE] VARCHAR(1),
    [COMMENT] VARCHAR(1024),
    [CONCURRENCY_CONTROL_NUMBER] BIGINT DEFAULT 1 NOT NULL,
    [APP_CREATE_USERID] VARCHAR(30) NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [APP_CREATE_USER_DIRECTORY] VARCHAR(12) NOT NULL,
    [APP_LAST_UPDATE_USERID] VARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [APP_LAST_UPDATE_USER_DIRECTORY] VARCHAR(12) NOT NULL,
    [DB_AUDIT_CREATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_CREATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL)
GO


INSERT INTO [dbo].[HMR_WILDLIFE_REPORT_TMP]
    ([WILDLIFE_RECORD_ID],[SUBMISSION_OBJECT_ID],[VALIDATION_STATUS_ID],[RECORD_TYPE],[SERVICE_AREA],[ACCIDENT_DATE],[TIME_OF_KILL],[LATITUDE],[LONGITUDE],[HIGHWAY_UNIQUE_NUMBER],[LANDMARK],[START_OFFSET],[NEAREST_TOWN],[WILDLIFE_SIGN],[QUANTITY],[SPECIES],[SEX],[AGE],[COMMENT],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_CREATE_USER_DIRECTORY],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[APP_LAST_UPDATE_USER_DIRECTORY],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP])
SELECT
    [WILDLIFE_RECORD_ID],[SUBMISSION_OBJECT_ID],[VALIDATION_STATUS_ID],[RECORD_TYPE],[SERVICE_AREA],[ACCIDENT_DATE],[TIME_OF_KILL],[LATITUDE],[LONGITUDE],[HIGHWAY_UNIQUE_NUMBER],[LANDMARK],[START_OFFSET],[NEAREST_TOWN],[WILDLIFE_SIGN],[QUANTITY],[SPECIES],[SEX],[AGE],[COMMENT],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_CREATE_USER_DIRECTORY],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[APP_LAST_UPDATE_USER_DIRECTORY],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP]
FROM [dbo].[HMR_WILDLIFE_REPORT]
GO


DROP INDEX [dbo].[HMR_WILDLIFE_REPORT].[HMR_WLDLF_RPT_SUBM_FK_I]
GO


DROP INDEX [dbo].[HMR_WILDLIFE_REPORT].[WLDLF_RPT_CNT_ARA_FK_I]
GO


DROP TABLE [dbo].[HMR_WILDLIFE_REPORT]
GO


EXEC sp_rename '[dbo].[HMR_WILDLIFE_REPORT_TMP]', 'HMR_WILDLIFE_REPORT', 'OBJECT'
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] ADD CONSTRAINT [HMR_WLDLF_RRT_PK] 
    PRIMARY KEY CLUSTERED ([WILDLIFE_RECORD_ID])
GO


CREATE NONCLUSTERED INDEX [HMR_WLDLF_RPT_SUBM_FK_I] ON [dbo].[HMR_WILDLIFE_REPORT] ([SUBMISSION_OBJECT_ID] ASC)
GO


CREATE NONCLUSTERED INDEX [WLDLF_RPT_CNT_ARA_FK_I] ON [dbo].[HMR_WILDLIFE_REPORT] ([SERVICE_AREA] ASC)
GO


EXECUTE sp_addextendedproperty N'MS_Description', N'Relative row number the record was located within a submission.', 'SCHEMA', N'dbo', 'TABLE', N'HMR_WILDLIFE_REPORT', 'COLUMN', N'ROW_NUM'
GO


/* ---------------------------------------------------------------------- */
/* Drop and recreate table "dbo.HMR_WORK_REPORT"                          */
/* ---------------------------------------------------------------------- */

GO


ALTER TABLE [dbo].[HMR_WORK_REPORT] DROP CONSTRAINT [HMR_WRK_RPT_PK]
GO


CREATE TABLE [dbo].[HMR_WORK_REPORT_TMP] (
    [WORK_REPORT_ID] NUMERIC(9) DEFAULT NEXT VALUE FOR [HMR_WRK_RPT_ID_SEQ] NOT NULL,
    [SUBMISSION_OBJECT_ID] NUMERIC(9) NOT NULL,
    [ROW_NUM] NUMERIC(9),
    [VALIDATION_STATUS_ID] NUMERIC(9),
    [RECORD_TYPE] VARCHAR(1),
    [SERVICE_AREA] NUMERIC(9) NOT NULL,
    [RECORD_NUMBER] VARCHAR(8),
    [TASK_NUMBER] VARCHAR(6),
    [ACTIVITY_NUMBER] VARCHAR(6),
    [START_DATE] DATE,
    [END_DATE] DATE,
    [ACCOMPLISHMENT] NUMERIC(7,2),
    [UNIT_OF_MEASURE] VARCHAR(12),
    [POSTED_DATE] DATE,
    [HIGHWAY_UNIQUE] VARCHAR(16),
    [LANDMARK] VARCHAR(8),
    [START_OFFSET] NUMERIC(7,3),
    [END_OFFSET] NUMERIC(7,3),
    [START_LATITUDE] NUMERIC(11,6),
    [START_LONGITUDE] NUMERIC(11,6),
    [END_LATITUDE] NUMERIC(11,6),
    [END_LONGITUDE] NUMERIC(11,6),
    [STRUCTURE_NUMBER] VARCHAR(5),
    [SITE_NUMBER] VARCHAR(8),
    [VALUE_OF_WORK] NUMERIC(8,2),
    [COMMENTS] VARCHAR(1024),
    [CONCURRENCY_CONTROL_NUMBER] BIGINT DEFAULT 1 NOT NULL,
    [APP_CREATE_USERID] VARCHAR(30) NOT NULL,
    [APP_CREATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_CREATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [APP_CREATE_USER_DIRECTORY] VARCHAR(12) NOT NULL,
    [APP_LAST_UPDATE_USERID] VARCHAR(30) NOT NULL,
    [APP_LAST_UPDATE_TIMESTAMP] DATETIME NOT NULL,
    [APP_LAST_UPDATE_USER_GUID] UNIQUEIDENTIFIER NOT NULL,
    [APP_LAST_UPDATE_USER_DIRECTORY] VARCHAR(12) NOT NULL,
    [DB_AUDIT_CREATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_CREATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_USERID] VARCHAR(30) DEFAULT user_name() NOT NULL,
    [DB_AUDIT_LAST_UPDATE_TIMESTAMP] DATETIME DEFAULT getutcdate() NOT NULL)
GO


INSERT INTO [dbo].[HMR_WORK_REPORT_TMP]
    ([WORK_REPORT_ID],[SUBMISSION_OBJECT_ID],[VALIDATION_STATUS_ID],[RECORD_TYPE],[SERVICE_AREA],[RECORD_NUMBER],[TASK_NUMBER],[ACTIVITY_NUMBER],[START_DATE],[END_DATE],[ACCOMPLISHMENT],[UNIT_OF_MEASURE],[POSTED_DATE],[HIGHWAY_UNIQUE],[LANDMARK],[START_OFFSET],[END_OFFSET],[START_LATITUDE],[START_LONGITUDE],[END_LATITUDE],[END_LONGITUDE],[STRUCTURE_NUMBER],[SITE_NUMBER],[VALUE_OF_WORK],[COMMENTS],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_CREATE_USER_DIRECTORY],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[APP_LAST_UPDATE_USER_DIRECTORY],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP])
SELECT
    [WORK_REPORT_ID],[SUBMISSION_OBJECT_ID],[VALIDATION_STATUS_ID],[RECORD_TYPE],[SERVICE_AREA],[RECORD_NUMBER],[TASK_NUMBER],[ACTIVITY_NUMBER],[START_DATE],[END_DATE],[ACCOMPLISHMENT],[UNIT_OF_MEASURE],[POSTED_DATE],[HIGHWAY_UNIQUE],[LANDMARK],[START_OFFSET],[END_OFFSET],[START_LATITUDE],[START_LONGITUDE],[END_LATITUDE],[END_LONGITUDE],[STRUCTURE_NUMBER],[SITE_NUMBER],[VALUE_OF_WORK],[COMMENTS],[CONCURRENCY_CONTROL_NUMBER],[APP_CREATE_USERID],[APP_CREATE_TIMESTAMP],[APP_CREATE_USER_GUID],[APP_CREATE_USER_DIRECTORY],[APP_LAST_UPDATE_USERID],[APP_LAST_UPDATE_TIMESTAMP],[APP_LAST_UPDATE_USER_GUID],[APP_LAST_UPDATE_USER_DIRECTORY],[DB_AUDIT_CREATE_USERID],[DB_AUDIT_CREATE_TIMESTAMP],[DB_AUDIT_LAST_UPDATE_USERID],[DB_AUDIT_LAST_UPDATE_TIMESTAMP]
FROM [dbo].[HMR_WORK_REPORT]
GO


DROP INDEX [dbo].[HMR_WORK_REPORT].[HMR_WRK_RRT_FK_I]
GO


DROP TABLE [dbo].[HMR_WORK_REPORT]
GO


EXEC sp_rename '[dbo].[HMR_WORK_REPORT_TMP]', 'HMR_WORK_REPORT', 'OBJECT'
GO


ALTER TABLE [dbo].[HMR_WORK_REPORT] ADD CONSTRAINT [HMR_WRK_RPT_PK] 
    PRIMARY KEY CLUSTERED ([WORK_REPORT_ID])
GO


CREATE NONCLUSTERED INDEX [HMR_WRK_RRT_FK_I] ON [dbo].[HMR_WORK_REPORT] ([SUBMISSION_OBJECT_ID] ASC)
GO


EXECUTE sp_addextendedproperty N'MS_Description', N'Relative row number the record was located within a submission.', 'SCHEMA', N'dbo', 'TABLE', N'HMR_WORK_REPORT', 'COLUMN', N'ROW_NUM'
GO


/* ---------------------------------------------------------------------- */
/* Add foreign key constraints                                            */
/* ---------------------------------------------------------------------- */

GO


ALTER TABLE [dbo].[HMR_ROCKFALL_REPORT] ADD CONSTRAINT [HMR_RCKFL_RPT_SUBM_OBJ_FK] 
    FOREIGN KEY ([SUBMISSION_OBJECT_ID]) REFERENCES [dbo].[HMR_SUBMISSION_OBJECT] ([SUBMISSION_OBJECT_ID])
GO


ALTER TABLE [dbo].[HMR_ROCKFALL_REPORT] ADD CONSTRAINT [HMR_RKFLL_RRT_SUBM_STAT_FK] 
    FOREIGN KEY ([VALIDATION_STATUS_ID]) REFERENCES [dbo].[HMR_SUBMISSION_STATUS] ([STATUS_ID])
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_ROW] ADD CONSTRAINT [HMR_SUBM_RW_SUBM_STAT_FK] 
    FOREIGN KEY ([ROW_STATUS_ID]) REFERENCES [dbo].[HMR_SUBMISSION_STATUS] ([STATUS_ID])
GO


ALTER TABLE [dbo].[HMR_SUBMISSION_ROW] ADD CONSTRAINT [HMR_SUBM_RW_HMR_SUBM_OBJ_FK] 
    FOREIGN KEY ([SUBMISSION_OBJECT_ID]) REFERENCES [dbo].[HMR_SUBMISSION_OBJECT] ([SUBMISSION_OBJECT_ID])
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] ADD CONSTRAINT [HMR_WLDLF_RPT_HMR_SRV_ARA_FK] 
    FOREIGN KEY ([SERVICE_AREA]) REFERENCES [dbo].[HMR_SERVICE_AREA] ([SERVICE_AREA_NUMBER])
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] ADD CONSTRAINT [HMR_WLDLF_RPT_SUBM_OBJ_FK] 
    FOREIGN KEY ([SUBMISSION_OBJECT_ID]) REFERENCES [dbo].[HMR_SUBMISSION_OBJECT] ([SUBMISSION_OBJECT_ID])
GO


ALTER TABLE [dbo].[HMR_WILDLIFE_REPORT] ADD CONSTRAINT [HMR_WLDLF_RRT_SUBM_STAT_FK] 
    FOREIGN KEY ([VALIDATION_STATUS_ID]) REFERENCES [dbo].[HMR_SUBMISSION_STATUS] ([STATUS_ID])
GO


ALTER TABLE [dbo].[HMR_WORK_REPORT] ADD CONSTRAINT [HMR_WRK_RRT_SUBM_STAT_FK] 
    FOREIGN KEY ([VALIDATION_STATUS_ID]) REFERENCES [dbo].[HMR_SUBMISSION_STATUS] ([STATUS_ID])
GO


ALTER TABLE [dbo].[HMR_WORK_REPORT] ADD CONSTRAINT [HMR_WRK_RRT_SUBM_OBJ_FK] 
    FOREIGN KEY ([SUBMISSION_OBJECT_ID]) REFERENCES [dbo].[HMR_SUBMISSION_OBJECT] ([SUBMISSION_OBJECT_ID])
GO


ALTER TABLE [dbo].[HMR_WORK_REPORT] ADD CONSTRAINT [HMR_WRK_RRT_SRV_ARA_FK] 
    FOREIGN KEY ([SERVICE_AREA]) REFERENCES [dbo].[HMR_SERVICE_AREA] ([SERVICE_AREA_NUMBER])
GO

