export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_USER_TYPES = 'FETCH_USER_TYPES';
export const FETCH_USER_STATUSES = 'FETCH_USER_STATUSES';

export const FETCH_SERVICE_AREAS = 'FETCH_SERVICE_AREAS';

export const FETCH_MAINTENANCE_TYPES = 'FETCH_MAINTENANCE_TYPES';
export const FETCH_UNIT_OF_MEASURES = 'FETCH_UNIT_OF_MEASURES';
export const FETCH_FEATURE_TYPES = 'FETCH_FEATURE_TYPES';
export const FETCH_LOCATION_CODES = 'FETCH_LOCATION_CODES';

export const FETCH_SUBMISSION_STATUSES = 'FETCH_SUBMISSION_STATUSES';

// Global Error Dialog
export const SHOW_ERROR_DIALOG_MODAL = 'SHOW_ERROR_DIALOG_MODAL';
export const HIDE_ERROR_DIALOG_MODAL = 'HIDE_ERROR_DIALOG_MODAL';
