export const FETCH_USER = 'FETCH_USER';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const SEARCH_USERS = 'SEARCH_USERS';
export const FETCH_USER_TYPES = 'FETCH_USER_TYPES';
export const FETCH_USER_STATUSES = 'FETCH_USER_STATUSES';
export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';

export const SET_SINGLE_USER_SEARCH_CRITERIA = 'SET_SINGLE_USER_SEARCH_CRITERIA';
export const SET_ALL_USER_SEARCH_CRITERIA = 'SET_ALL_USER_SEARCH_CRITERIA';

export const FETCH_SERVICE_AREAS = 'FETCH_SERVICE_AREAS';

export const FETCH_ROLES = 'FETCH_ROLES';
export const SEARCH_ROLES = 'SEARCH_ROLES';

export const SET_SINGLE_ROLE_SEARCH_CRITERIA = 'SET_SINGLE_ROLE_SEARCH_CRITERIA';

// Global Error Dialog
export const SHOW_ERROR_DIALOG_MODAL = 'SHOW_ERROR_DIALOG_MODAL';
export const HIDE_ERROR_DIALOG_MODAL = 'HIDE_ERROR_DIALOG_MODAL';
