export const FETCH_USER = 'FETCH_USER';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER_TYPES = 'FETCH_USER_TYPES';
export const FETCH_USER_STATUSES = 'FETCH_USER_STATUSES';
export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';

export const FETCH_SERVICE_AREAS = 'FETCH_SERVICE_AREAS';

export const FETCH_ROLES = 'FETCH_ROLES';

// Global Error Dialog
export const SHOW_ERROR_DIALOG_MODAL = 'SHOW_ERROR_DIALOG_MODAL';
export const HIDE_ERROR_DIALOG_MODAL = 'HIDE_ERROR_DIALOG_MODAL';
